function buildEntries(items) {
  return items.map(([english, japanese, explanation]) => ({
    english,
    japanese,
    explanation
  }));
}

function dedupeEntries(items) {
  const seen = new Set();

  return items.filter(({ english }) => {
    const key = english.trim().toLowerCase();

    if (seen.has(key)) {
      return false;
    }

    seen.add(key);
    return true;
  });
}

function withSharedExplanation(pairs, explanation) {
  return pairs.map(([english, japanese]) => [english, japanese, explanation]);
}

const legacyPhrases = {
  beginner: {
    label: "初級",
    description: "まずは短くて使いやすい基本フレーズから身につけるレベルです。",
    words: buildEntries([
      ["How are you?", "お元気ですか", "相手の体調や近況をたずねる定番のあいさつです。会話の最初に使いやすく、親しい相手にも初対面にも幅広く使えます。"],
      ["I am fine.", "元気です", "体調や気分を聞かれたときの基本的な返答です。短く答えたいときは I'm fine. の形で自然に使えます。"],
      ["Nice to meet you.", "はじめまして", "初対面のあいさつで使う定番表現です。自己紹介の直後に添えると自然で丁寧な印象になります。"],
      ["Thank you very much.", "どうもありがとうございます", "感謝をしっかり伝えたいときの表現です。Thank you. より丁寧で、店員や目上の相手にも使いやすいです。"],
      ["You're welcome.", "どういたしまして", "相手に感謝されたときの基本的な返答です。会話をやわらかく締めるときに便利です。"],
      ["Excuse me.", "すみません", "呼びかけ、軽い謝罪、通してもらうときなど幅広く使える万能表現です。まず相手の注意を引きたいときに使います。"],
      ["I'm sorry.", "ごめんなさい", "自分の非を認めて謝るときの基本表現です。Excuse me. より謝罪の意味が強い場面で使います。"],
      ["No problem.", "大丈夫です", "謝られたりお願いされたりしたときに、気にしなくてよいことを伝える表現です。くだけすぎず日常会話で使いやすいです。"],
      ["Please help me.", "手伝ってください", "困っていて助けが必要なときに直接伝える表現です。緊急時にも通じやすい短い言い方です。"],
      ["I don't know.", "わかりません", "答えがわからないときに使う基本表現です。無理に答えられない場面で自然に使えます。"],
      ["I understand.", "わかりました", "説明を理解したことを伝える表現です。相手の話を受け止めたことを示すのに便利です。"],
      ["Could you say that again?", "もう一度言ってもらえますか", "聞き取れなかった内容を丁寧に言い直してもらう表現です。会話を止めすぎずに確認できます。"],
      ["Please speak slowly.", "ゆっくり話してください", "相手の話す速度が速いときにペースを落としてもらう表現です。英語に不慣れなことを自然に伝えられます。"],
      ["What does this mean?", "これはどういう意味ですか", "言葉や表示の意味をたずねる表現です。この this には単語、文、標識など幅広い対象を置けます。"],
      ["How much is this?", "これはいくらですか", "値段を聞くときの基本表現です。商品を指しながら言うだけで通じやすいので買い物で非常に便利です。"],
      ["I would like this.", "これをください", "欲しいものを指して伝える表現です。注文や買い物で丁寧に希望を伝えたいときに使えます。"],
      ["Where is the station?", "駅はどこですか", "目的地の場所をたずねる基本表現です。station を restroom や bus stop など別の名詞に置き換えて応用できます。"],
      ["Where is the restroom?", "トイレはどこですか", "場所を聞く定番表現で、旅行中にも非常に使用頻度が高いです。急いでいるときでも短くはっきり伝わります。"],
      ["Can I sit here?", "ここに座ってもいいですか", "席を使ってよいか確認する表現です。人の近くに座る前に言うと丁寧です。"],
      ["Can I use Wi-Fi here?", "ここでWi-Fiは使えますか", "店や施設でネット接続の有無を確認する表現です。旅行者には特に実用的なフレーズです。"]
    ])
  },
  intermediate: {
    label: "中級",
    description: "日常会話や予定調整でよく使う表現を扱うレベルです。",
    words: buildEntries([
      ["Could you recommend something popular?", "人気のあるものをおすすめしてもらえますか", "店員や現地の人に定番を聞きたいときの表現です。something popular によって「人気のもの」という幅広い聞き方ができます。"],
      ["I have a reservation under this name.", "この名前で予約しています", "ホテルやレストランで予約を伝える定番表現です。under this name は「この名前で」という予約確認の言い回しです。"],
      ["Can I change my order?", "注文を変更できますか", "注文内容を修正したいときに使う表現です。レストランだけでなくオンライン注文の確認でも使えます。"],
      ["I'd like to pay by card.", "カードで支払いたいです", "支払い方法を伝える自然な表現です。by card を by cash に替えると現金払いにも応用できます。"],
      ["Could you make it a little less spicy?", "少し辛さを控えてもらえますか", "料理の味つけをやわらかく調整してもらいたいときの表現です。less spicy の形で辛さを下げたいことを伝えます。"],
      ["I'm on my way now.", "今向かっています", "待ち合わせ相手に現在移動中だと伝えるときの表現です。到着が近いことを自然に伝えられます。"],
      ["I might be a little late.", "少し遅れるかもしれません", "時間に遅れそうなときに早めに連絡する表現です。might を使うことで断定せず柔らかく伝えられます。"],
      ["Can we meet somewhere else?", "別の場所で会えますか", "待ち合わせ場所を変更したいときの表現です。somewhere else で「ほかのどこか」という自然な言い回しになります。"],
      ["Please let me know when you arrive.", "着いたら知らせてください", "相手の到着連絡をお願いする表現です。待ち合わせや荷物の受け取り時によく使います。"],
      ["That sounds like a good idea.", "それはよさそうですね", "提案に対して前向きに反応するときの自然な表現です。完全に確定ではなく、好意的に受け止めるニュアンスがあります。"],
      ["Could you give me a hand?", "手を貸してもらえますか", "give me a hand は「手伝う」という意味の口語表現です。重い物を持つときや作業を少し助けてほしいときに使います。"],
      ["I'm not used to this yet.", "まだこれに慣れていません", "not used to で「〜に慣れていない」という状態を表します。新しい仕事や環境に慣れていないことを自然に伝えられます。"],
      ["How long does it take from here?", "ここからどのくらいかかりますか", "所要時間をたずねる表現です。徒歩、車、電車など移動手段を問わず使える便利な聞き方です。"],
      ["Do I need to transfer?", "乗り換えは必要ですか", "電車やバスの移動中に使う実用的な表現です。transfer は交通機関の「乗り換え」を指します。"],
      ["Can I leave my luggage here?", "ここに荷物を置いてもいいですか", "ホテルや店で荷物を預けたいときの表現です。leave はこの場合「置いていく、預ける」の意味です。"],
      ["I'm just looking around.", "見ているだけです", "店員に話しかけられたときによく使う表現です。買うかどうか決めていない状態をやわらかく伝えられます。"],
      ["Could I get a receipt, please?", "領収書をもらえますか", "支払い後にレシートや領収書をお願いする表現です。ビジネスでも旅行でも使用頻度が高いです。"],
      ["Could you explain it in simple words?", "簡単な言葉で説明してもらえますか", "難しい説明をもっとわかりやすくしてほしいときの表現です。学習中の会話で特に便利です。"],
      ["I'm looking forward to it.", "楽しみにしています", "未来の予定を前向きに待っていることを伝える定番表現です。会話でもメールでも使えます。"],
      ["Can we split the bill?", "割り勘にできますか", "レストランで会計を分けたいときの定番表現です。split the bill で「勘定を分ける」という意味になります。"]
    ])
  },
  advanced: {
    label: "上級",
    description: "意見交換や説明で役立つ、少し踏み込んだ表現を扱うレベルです。",
    words: buildEntries([
      ["From my point of view, this is the best option.", "私の見方ではこれが最善の選択です", "From my point of view は「私の観点では」という前置きで、自分の意見だと示しつつ丁寧に主張できます。"],
      ["I'm not completely convinced yet.", "まだ完全には納得していません", "相手を強く否定せずに懸念を示す表現です。completely を使うことで「一部は理解しているが十分ではない」と伝えられます。"],
      ["That makes sense to me.", "それは筋が通っていると思います", "相手の説明が理解でき、納得できるときの表現です。会話を前向きに進めるクッションにもなります。"],
      ["I see where you're coming from.", "言いたいことはわかります", "直訳ではなく、相手の立場や発想を理解したときに使う慣用表現です。全面同意ではなく理解を示すときに便利です。"],
      ["Let me think it through for a moment.", "少し整理して考えさせてください", "think it through は「最後までしっかり考える」という意味です。即答を避け、丁寧に時間をもらいたいときに使います。"],
      ["Could we go over the details once more?", "詳細をもう一度確認できますか", "go over は「見直す、確認する」という意味で、内容を再点検したいときに便利な表現です。"],
      ["We should take that possibility into account.", "その可能性も考慮すべきです", "take A into account で「Aを考慮に入れる」という意味です。議論で抜けている視点を足すときに使います。"],
      ["I'd rather not make a quick decision.", "性急に決めたくはありません", "I'd rather not は「できれば〜したくない」という丁寧な断り方です。慎重に進めたい姿勢を示せます。"],
      ["Could you be a bit more specific?", "もう少し具体的に言ってもらえますか", "specific は「具体的な」という意味です。抽象的な説明を深掘りしたいときによく使います。"],
      ["I don't want to jump to conclusions.", "早合点はしたくありません", "jump to conclusions は「十分な情報なしに結論を急ぐ」という意味の熟語です。慎重な姿勢を示すときに使います。"],
      ["Let's take a step back for a second.", "少し立ち止まって考えましょう", "議論が細かくなりすぎたときに、一度視点を引いて整理したいときの表現です。"],
      ["There seems to be a misunderstanding.", "誤解があるようです", "直接的に相手を責めず、状況として誤解が起きていることを示す言い方です。"],
      ["I appreciate your honesty.", "率直に話してくれて感謝します", "率直な意見や厳しい指摘を受けたときでも前向きに受け止める表現です。関係を保ちながら会話できます。"],
      ["This could cause problems later on.", "これは後で問題になるかもしれません", "later on は「この先で、その後に」という意味です。今は小さく見える問題の将来リスクを指摘するときに使います。"],
      ["I want to make sure we're on the same page.", "認識をそろえておきたいです", "on the same page は「同じ理解をしている」という意味の慣用表現です。会議や打ち合わせで非常によく使います。"],
      ["We need to strike a balance.", "バランスを取る必要があります", "strike a balance は「ちょうどよいバランスを見つける」という意味の表現で、複数の要素の調整時に使われます。"]
    ])
  },
  business: {
    label: "ビジネス",
    description: "仕事の会話やメール、会議で使いやすい表現を扱うレベルです。",
    words: buildEntries([
      ["Could we schedule a meeting for next week?", "来週ミーティングを設定できますか", "schedule a meeting は会議日程を入れる定番表現です。next week を変えるだけで日時調整に広く使えます。"],
      ["Thank you for your quick response.", "迅速なご返信ありがとうございます", "メールの冒頭で非常によく使うお礼表現です。quick response により返答の速さへの感謝が明確になります。"],
      ["Please find the attached file.", "添付ファイルをご確認ください", "メールで資料を送るときの定番表現です。ややフォーマルで、ビジネス文書にそのまま使えます。"],
      ["Let me share the latest update.", "最新の状況を共有します", "会議やメールで進捗共有を始めるときに使いやすい一文です。update は「更新情報、進捗」の意味で便利です。"],
      ["We are currently reviewing the proposal.", "現在提案内容を確認中です", "reviewing the proposal で「提案を検討している最中」と伝えられます。即答できないときに自然です。"],
      ["Could you confirm your availability?", "ご都合を確認させてください", "availability は空き状況や対応可能時間を指します。会議設定や訪問日調整でよく使います。"],
      ["I'll get back to you by tomorrow.", "明日までにご連絡します", "get back to you は「折り返し連絡する」という定番表現です。回答期限を添えるとより実務的です。"],
      ["Please let me know if you have any questions.", "ご不明点があればお知らせください", "メールの締めとして非常に自然な表現です。相手に質問しやすい空気を作れます。"],
      ["We need to adjust the schedule slightly.", "スケジュールを少し調整する必要があります", "大きな変更ではなく微調整だと伝えたいときに slightly が効きます。相手への負担感を和らげられます。"],
      ["The meeting has been moved to Friday.", "会議は金曜日に変更になりました", "has been moved は日程変更を伝える受け身の定番表現です。会議、納期、予約などにも応用できます。"],
      ["Could you send me the revised version?", "修正版を送っていただけますか", "revised version は修正済みの版を指します。資料や契約書のやり取りでよく出ます。"],
      ["I'd appreciate your feedback.", "ご意見をいただけると助かります", "I'd appreciate ... は丁寧な依頼表現です。feedback のほか input, advice などにも応用できます。"],
      ["We're on track so far.", "今のところ順調です", "on track は「計画どおりに進んでいる」という意味の慣用表現です。進捗報告で使いやすいです。"],
      ["We're slightly behind schedule.", "少し予定より遅れています", "behind schedule で「予定より遅れている」という意味です。slightly を入れると深刻さを調整できます。"],
      ["I'd like to clarify one point.", "一点確認したいことがあります", "clarify は「明確にする」です。細部の認識違いを防ぐための切り出しとして便利です。"],
      ["Let's align on the next steps.", "次の進め方をそろえましょう", "align on ... は「〜について認識を一致させる」というビジネス頻出表現です。"],
      ["I'll take care of the follow-up.", "フォローは私が対応します", "take care of ... で「〜を引き受ける」という意味です。次のアクションを自分が持つときに便利です。"],
      ["We need approval before moving forward.", "先に承認が必要です", "moving forward は「先へ進む」という意味で、承認待ちの状況説明によく使われます。"],
      ["Please keep me posted.", "進捗を共有してください", "短く自然に「最新状況を知らせてほしい」と伝える表現です。メールでも口頭でも使いやすいです。"],
      ["Could you review this by end of day?", "今日中に確認していただけますか", "by end of day は「本日中に」という意味で、レビュー期限をやわらかく示せます。"]
    ])
  },
  travel: {
    label: "旅行",
    description: "道案内、チェックイン、注文、トラブル対応など旅行でそのまま使える表現です。",
    words: buildEntries([
      ["Where can I buy a train ticket?", "電車の切符はどこで買えますか", "buy a train ticket で切符購入をたずねる表現です。駅員や案内所でそのまま使いやすい質問です。"],
      ["Which platform should I go to?", "どのホームに行けばいいですか", "platform は電車のホームを指します。should I go to の形で「行くべき場所」を自然に聞けます。"],
      ["Does this train stop at the airport?", "この電車は空港に止まりますか", "stop at ... で「〜に停車する」という意味です。目的地に行く電車か確認するのに便利です。"],
      ["How often does the bus come?", "バスはどのくらいの間隔で来ますか", "頻度や間隔を知りたいときの表現です。時刻表が読みにくいときにも使えます。"],
      ["Could you tell me when to get off?", "降りるときに教えてもらえますか", "get off は乗り物を降りるという意味です。目的地が不安なときに運転手や近くの人へ頼めます。"],
      ["Is this the right way to the museum?", "博物館へはこの道で合っていますか", "right way to ... は「〜へ行く正しい道」という意味です。地図を見ながら確認するときに便利です。"],
      ["How far is it from here?", "ここからどのくらい遠いですか", "距離感をたずねる基本表現です。徒歩圏かどうかを判断したいときにも使えます。"],
      ["Can I walk there?", "歩いて行けますか", "歩いて向かえる距離か確認したいときの表現です。タクシーやバスが必要かの判断にも役立ちます。"],
      ["Could you point it out on the map?", "地図で指してもらえますか", "point out は「指し示す」という意味です。言葉だけだとわからないときに視覚的な説明をお願いできます。"],
      ["I'm lost.", "道に迷いました", "短くはっきり助けを求められる表現です。困っていることがすぐ伝わるので旅行中に覚えておくと安心です。"],
      ["Can you call a taxi for me?", "タクシーを呼んでもらえますか", "ホテルや店でタクシー手配を頼む定番表現です。for me を付けることで依頼が明確になります。"],
      ["How much is the fare to downtown?", "市内中心部までの料金はいくらですか", "fare は乗り物の運賃を表します。タクシーやシャトルの目安を確認するのに役立ちます。"],
      ["Please take me to this address.", "この住所までお願いします", "タクシー運転手に目的地を見せながら伝える実用表現です。紙やスマホ画面と一緒に使うと確実です。"],
      ["I have a reservation for tonight.", "今夜の予約があります", "ホテルやレストランで予約を伝えるときに使う表現です。for tonight の部分は日付に変えて応用できます。"],
      ["I'd like to check in.", "チェックインしたいです", "ホテル到着時の基本表現です。短くても十分伝わるので覚えておくと便利です。"],
      ["Could I leave my luggage before check-in?", "チェックイン前に荷物を預けられますか", "到着が早いときによく使う表現です。leave my luggage で荷物を預ける意味になります。"],
      ["What time is breakfast served?", "朝食は何時からですか", "ホテルで朝食時間を確認する定番表現です。served を使うと提供時間を自然に聞けます。"],
      ["Could I get a room with a view?", "景色のいい部屋にできますか", "with a view で「眺めのある、景色のよい」という意味です。部屋の希望を丁寧に伝えられます。"],
      ["The air conditioner isn't working.", "エアコンが動いていません", "設備トラブルを伝える実用表現です。working を使うと「正常に機能していない」ことが自然に伝わります。"],
      ["I'd like to check out.", "チェックアウトしたいです", "ホテルを出るときの定番表現です。請求や荷物確認の流れに入るきっかけになります。"],
      ["Do you have a table for two?", "2人用の席はありますか", "レストラン入店時の定番表現です。人数を変えるだけでそのまま応用できます。"],
      ["What do you recommend here?", "このお店のおすすめは何ですか", "店員に人気メニューや看板料理を聞く自然な表現です。注文で迷ったときに非常に便利です。"],
      ["I'd like this without onions.", "これは玉ねぎ抜きでお願いします", "without ... で「〜なしで」という意味です。苦手な食材やアレルギー対応でよく使います。"],
      ["Can you make it less spicy?", "辛さを控えめにできますか", "less spicy で辛さを下げてもらう表現です。味の調整を頼むときにそのまま使えます。"],
      ["Could I get the bill, please?", "お会計をお願いします", "bill はレストランでの会計を指します。食事が終わったあとに店員へ自然に頼めます。"],
      ["Can I pay separately?", "別々に払えますか", "友人や同僚と会計を分けたいときの表現です。旅行中の食事でよく使います。"],
      ["I'm looking for a pharmacy.", "薬局を探しています", "薬局の場所を聞く前置きとして使える表現です。I’m looking for ... は探し物全般に応用できます。"],
      ["Do you sell medicine for a headache?", "頭痛薬はありますか", "症状に合う薬を探すときの表現です。for a headache の部分を stomachache などに替えて使えます。"],
      ["I need a doctor.", "医者が必要です", "体調不良やけがの際に、短く強く必要性を伝える表現です。緊急時に覚えておく価値があります。"],
      ["I've lost my passport.", "パスポートをなくしました", "重要書類の紛失を伝える表現です。警察やホテル、空港でまず状況説明として使えます。"],
      ["My bag has been stolen.", "かばんを盗まれました", "盗難被害を伝えるときの表現です。has been stolen の受け身で「盗まれた状態」をはっきり示せます。"],
      ["Could you call the police?", "警察を呼んでもらえますか", "トラブル時に第三者へ助けを求める非常に実用的な表現です。call the police は緊急性が高い場面で使います。"],
      ["Is there an ATM nearby?", "近くにATMはありますか", "現金が必要なときに場所を聞く基本表現です。nearby を使うと近くで探していることが伝わります。"],
      ["Can I exchange money here?", "ここで両替できますか", "空港やホテルで両替可能か確認する表現です。exchange money で「お金を両替する」を表します。"],
      ["What time does the museum open?", "その博物館は何時に開きますか", "観光施設の営業時間を確認する表現です。museum を station, store, temple などに替えて応用できます。"],
      ["Are there any tickets left for today?", "今日のチケットはまだありますか", "left はここでは「残っている」という意味です。当日券の有無をたずねるのに便利です。"],
      ["Could you take our picture?", "写真を撮ってもらえますか", "観光地で人に撮影をお願いするときの定番表現です。our picture で自分たちの写真という意味になります。"],
      ["Where is the boarding gate?", "搭乗口はどこですか", "空港で最重要レベルに実用的な表現です。gate 番号がわかっていても方向確認に使えます。"],
      ["Be careful of slippery floors.", "床が滑りやすいので気をつけてください", "be careful of ... は「〜に注意する」「〜に気をつける」という意味の熟語で、人、物、場所、状況など具体的な対象に対して注意を促す際に使われます。危険なものや注意すべき対象の前に置いて使います。ここでは slippery floors で「滑りやすい床」に注意を促しています。"]
    ])
  }
};

const basicPhraseExpansion = [
  ...withSharedExplanation([
    ["Good morning.", "おはようございます"],
    ["Good afternoon.", "こんにちは"],
    ["Good evening.", "こんばんは"],
    ["See you later.", "またあとで"],
    ["See you tomorrow.", "また明日"],
    ["Have a nice day.", "よい一日を"],
    ["Have a good trip.", "よい旅を"],
    ["Take care.", "気をつけて"],
    ["Welcome back.", "おかえりなさい"],
    ["Long time no see.", "久しぶりですね"],
    ["How was your day?", "今日はどんな一日でしたか"],
    ["I'm ready.", "準備できています"],
    ["I'm coming.", "今行きます"],
    ["It's okay.", "大丈夫です"],
    ["That's fine.", "それで大丈夫です"],
    ["Sounds great.", "よさそうです"],
    ["I'm excited.", "わくわくしています"],
    ["I'm nervous.", "緊張しています"],
    ["I'm happy.", "うれしいです"]
  ], "あいさつやその場の気持ちを短く伝える基本フレーズです。会話の最初や返事としてそのまま使いやすい表現をまとめています。"),
  ...withSharedExplanation([
    ["I'm thirsty.", "のどが渇いています"],
    ["I'm cold.", "寒いです"],
    ["I'm hot.", "暑いです"],
    ["I'm sleepy.", "眠いです"],
    ["I'm busy.", "忙しいです"],
    ["I'm free now.", "今は空いています"],
    ["I'm at home.", "家にいます"],
    ["I'm outside.", "外にいます"],
    ["I'm in a hurry.", "急いでいます"],
    ["I need water.", "水が必要です"],
    ["I need help.", "助けが必要です"],
    ["I need a break.", "少し休憩が必要です"],
    ["I need a pen.", "ペンが必要です"],
    ["I need a charger.", "充電器が必要です"],
    ["I want coffee.", "コーヒーが欲しいです"],
    ["I want tea.", "お茶が欲しいです"],
    ["I want some rest.", "少し休みたいです"],
    ["I feel better.", "気分がよくなりました"],
    ["I feel sick.", "気分が悪いです"]
  ], "自分の体調や今の状態をシンプルに伝えるときのフレーズです。旅行中や日常会話で特に出番が多い表現です。"),
  ...withSharedExplanation([
    ["Please wait here.", "ここで待ってください"],
    ["Please sit down.", "座ってください"],
    ["Please open the door.", "ドアを開けてください"],
    ["Please close the window.", "窓を閉めてください"],
    ["Please look at this.", "これを見てください"],
    ["Please read this.", "これを読んでください"],
    ["Please write your name.", "名前を書いてください"],
    ["Please speak louder.", "もう少し大きな声で話してください"],
    ["Say it again, please.", "もう一度言ってください"],
    ["Say that slowly, please.", "それをゆっくり言ってください"],
    ["What is your name?", "お名前は何ですか"],
    ["How do you spell it?", "それはどうつづりますか"],
    ["What time is it?", "何時ですか"],
    ["What day is it today?", "今日は何曜日ですか"],
    ["Can you help me?", "手伝ってもらえますか"],
    ["Can you repeat that?", "それを繰り返してもらえますか"],
    ["Do you understand?", "わかりますか"],
    ["I have a question.", "質問があります"],
    ["I forgot.", "忘れました"]
  ], "相手にお願いしたり、会話を続けたりするための超基本フレーズです。学校、職場、日常のどこでも応用しやすい形です。"),
  ...withSharedExplanation([
    ["I want this one.", "これが欲しいです"],
    ["I don't need a bag.", "袋はいりません"],
    ["Please make it hot.", "温かくしてください"],
    ["Please make it cold.", "冷たくしてください"],
    ["Just a little.", "少しだけで大丈夫です"],
    ["That's enough.", "それで十分です"],
    ["I like this color.", "この色が好きです"],
    ["This is too big.", "これは大きすぎます"],
    ["This is too small.", "これは小さすぎます"],
    ["Do you have a larger size?", "もっと大きいサイズはありますか"],
    ["Do you have a smaller size?", "もっと小さいサイズはありますか"],
    ["Can I try this on?", "これを試着できますか"],
    ["Where is the cashier?", "レジはどこですか"],
    ["I'd like some water.", "お水をお願いします"],
    ["I'd like some bread.", "パンをお願いします"],
    ["No ice, please.", "氷なしでお願いします"],
    ["More water, please.", "お水をもう少しお願いします"],
    ["Is this fresh?", "これは新鮮ですか"],
    ["This looks good.", "おいしそうです"],
    ["I'll take it.", "これにします"]
  ], "買い物や飲食店でそのまま使いやすい短いフレーズです。サイズ、注文、受け答えの基本をまとめています。"),
  ...withSharedExplanation([
    ["Where is the bathroom?", "トイレはどこですか"],
    ["Where is the exit?", "出口はどこですか"],
    ["Where is the entrance?", "入口はどこですか"],
    ["Where is the bus stop?", "バス停はどこですか"],
    ["Where is the hotel?", "ホテルはどこですか"],
    ["Where is the park?", "公園はどこですか"],
    ["Where is the supermarket?", "スーパーはどこですか"],
    ["Where is the pharmacy?", "薬局はどこですか"],
    ["Is it far?", "遠いですか"],
    ["Is it near here?", "この近くですか"],
    ["Go straight.", "まっすぐ進んでください"],
    ["Turn left here.", "ここで左に曲がってください"],
    ["Turn right there.", "あそこで右に曲がってください"],
    ["It's on this street.", "この通りにあります"],
    ["It's across the street.", "道の向かい側です"],
    ["It's next to the station.", "駅の隣です"],
    ["It's behind the building.", "建物の後ろです"],
    ["I'm lost.", "道に迷いました"],
    ["Please show me on the map.", "地図で見せてください"],
    ["Let's go upstairs.", "上に行きましょう"]
  ], "道案内や場所確認で役立つフレーズです。場所をたずねるだけでなく、方向を伝える表現も一緒に覚えられます。"),
  ...withSharedExplanation([
    ["It's early.", "まだ早いです"],
    ["It's late.", "もう遅いです"],
    ["It's my day off.", "今日は休みです"],
    ["I work today.", "今日は仕事です"],
    ["I study every day.", "毎日勉強しています"],
    ["I cook at home.", "家で料理します"],
    ["I walk every morning.", "毎朝歩きます"],
    ["I go to bed early.", "早く寝ます"],
    ["I wake up at six.", "6時に起きます"],
    ["I eat lunch here.", "ここで昼ごはんを食べます"],
    ["I eat dinner at home.", "家で夕ごはんを食べます"],
    ["Let's meet at noon.", "正午に会いましょう"],
    ["Let's meet at seven.", "7時に会いましょう"],
    ["I'm on my way.", "向かっています"],
    ["I'm almost done.", "もうすぐ終わります"],
    ["I have time now.", "今は時間があります"],
    ["I have no plans today.", "今日は予定がありません"],
    ["Today is busy.", "今日は忙しいです"],
    ["Tomorrow is better.", "明日のほうが都合がいいです"],
    ["This weekend works for me.", "今週末なら大丈夫です"]
  ], "時間、予定、日々の行動について話すときに便利な基本フレーズです。約束や日常会話で出番が多い表現を集めています。"),
  ...withSharedExplanation([
    ["This is my family.", "こちらは私の家族です"],
    ["He is my brother.", "彼は私の兄弟です"],
    ["She is my sister.", "彼女は私の姉妹です"],
    ["We are classmates.", "私たちはクラスメートです"],
    ["We are neighbors.", "私たちは近所同士です"],
    ["My room is small.", "私の部屋は小さいです"],
    ["My house is clean.", "私の家はきれいです"],
    ["The food is delicious.", "料理がおいしいです"],
    ["The coffee is strong.", "コーヒーが濃いです"],
    ["The music is loud.", "音楽が大きいです"],
    ["The room is quiet.", "部屋は静かです"],
    ["The weather is nice.", "天気がいいです"],
    ["It looks beautiful.", "きれいに見えます"],
    ["It smells good.", "いい匂いがします"],
    ["It tastes sweet.", "甘い味がします"],
    ["It tastes salty.", "しょっぱい味がします"],
    ["I like this place.", "この場所が好きです"],
    ["I miss home.", "家が恋しいです"],
    ["Let's take a picture.", "写真を撮りましょう"]
  ], "人や場所、食べ物などの印象をシンプルに伝えるフレーズです。身近な話題で会話を広げる練習に向いています。"),
  ...withSharedExplanation([
    ["Can we start now?", "今始められますか"],
    ["Can we finish now?", "今終えられますか"],
    ["Can I join you?", "一緒に参加してもいいですか"],
    ["Can I go first?", "先に行ってもいいですか"],
    ["Can I pay now?", "今払ってもいいですか"],
    ["Can I open it?", "開けてもいいですか"],
    ["Can I close it?", "閉めてもいいですか"],
    ["Can I use your pen?", "あなたのペンを使ってもいいですか"],
    ["Can I borrow this?", "これを借りてもいいですか"],
    ["Can I charge my phone here?", "ここでスマホを充電してもいいですか"],
    ["Do you have Wi-Fi?", "Wi-Fiはありますか"],
    ["Do you have change?", "小銭はありますか"],
    ["Do you have time?", "時間はありますか"],
    ["Do you live nearby?", "この近くに住んでいますか"],
    ["Do you work here?", "ここで働いていますか"],
    ["Do you study English?", "英語を勉強していますか"],
    ["Are you ready?", "準備はできていますか"],
    ["Are you okay?", "大丈夫ですか"],
    ["Are you hungry?", "お腹は空いていますか"],
    ["Are you tired?", "疲れていますか"]
  ], "許可を求めたり、相手の状況をたずねたりする日常フレーズです。短くて覚えやすく、会話の回転をよくしてくれます。"),
  ...withSharedExplanation([
    ["Really?", "本当ですか"],
    ["I agree.", "賛成です"],
    ["Maybe later.", "またあとでかもしれません"],
    ["Not now.", "今ではありません"],
    ["Of course.", "もちろんです"],
    ["That's interesting.", "それはおもしろいですね"],
    ["That's funny.", "それはおかしいですね"],
    ["That's easy.", "それは簡単です"],
    ["That's difficult.", "それは難しいです"],
    ["It's my first time.", "初めてです"],
    ["I remember now.", "今思い出しました"],
    ["I understand a little.", "少しわかります"],
    ["I need practice.", "練習が必要です"],
    ["English is hard.", "英語は難しいです"],
    ["English is fun.", "英語は楽しいです"],
    ["Let's try again.", "もう一度やってみましょう"],
    ["I'll do my best.", "がんばります"],
    ["Please call me later.", "あとで電話してください"],
    ["Send me a message.", "メッセージを送ってください"],
    ["See you soon.", "またすぐ会いましょう"]
  ], "短い相づちや感想、やる気を伝えるフレーズです。会話の返しに困りにくくなるので初級で特に役立ちます。")
];

const practicalPhraseExpansion = [
  ...withSharedExplanation([
    ["What do you mean by that?", "それはどういう意味ですか"],
    ["Could you explain that part?", "その部分を説明してもらえますか"],
    ["Could you speak a little slower?", "もう少しゆっくり話してもらえますか"],
    ["Could you say it in another way?", "別の言い方で言ってもらえますか"],
    ["I'm not following you.", "話についていけていません"],
    ["I'm not sure I understood.", "理解できたか少し自信がありません"],
    ["Let me make sure I got that right.", "正しく理解できたか確認させてください"],
    ["So what you're saying is ...", "つまりおっしゃっているのは…ということですか"],
    ["Is that what you mean?", "そういう意味ですか"],
    ["Can you give me more details?", "もう少し詳しく教えてもらえますか"],
    ["What's the main point?", "要点は何ですか"],
    ["What should I focus on?", "何に集中すればいいですか"],
    ["Could you type that for me?", "それを入力してもらえますか"],
    ["Could you send me an example?", "例を送ってもらえますか"],
    ["I need a clearer explanation.", "もう少し分かりやすい説明が必要です"],
    ["Can we go over it step by step?", "順を追って確認できますか"],
    ["I want to make sure I understood correctly.", "正しく理解できたか確かめたいです"],
    ["That's a new word for me.", "それは私にとって新しい単語です"]
  ], "聞き返しや説明の確認で役立つ実用フレーズです。相手に失礼になりにくく、会話を止めずに理解を深められます。"),
  ...withSharedExplanation([
    ["Would tomorrow work for you?", "明日で大丈夫ですか"],
    ["How about sometime this afternoon?", "今日の午後のどこかはどうですか"],
    ["I'm available after six.", "6時以降なら空いています"],
    ["I'm free until noon.", "正午までは空いています"],
    ["I need to move our plan back a little.", "予定を少し後ろにずらしたいです"],
    ["Can we make it a bit later?", "少し遅らせられますか"],
    ["Can we start earlier?", "もっと早く始められますか"],
    ["Let's set a time now.", "今ここで時間を決めましょう"],
    ["I'll let you know by tonight.", "今夜までに連絡します"],
    ["I'm waiting for a reply.", "返事を待っています"],
    ["I need to check with someone first.", "まず誰かに確認する必要があります"],
    ["This time works better for me.", "この時間のほうが都合がいいです"],
    ["I can stay for about an hour.", "1時間くらいならいられます"],
    ["I may be delayed by traffic.", "交通事情で遅れるかもしれません"],
    ["Please tell me if anything changes.", "何か変わったら教えてください"],
    ["Let's keep in touch about it.", "その件は連絡を取り合いましょう"],
    ["I can adjust my schedule.", "予定は調整できます"],
    ["We should leave a little earlier.", "少し早めに出たほうがよさそうです"]
  ], "日程調整や待ち合わせで使いやすいフレーズです。予定を決める、ずらす、連絡する流れを自然に言えるようになります。"),
  ...withSharedExplanation([
    ["I'd rather stay here.", "むしろここにいたいです"],
    ["I'd rather go by train.", "むしろ電車で行きたいです"],
    ["I prefer something simple.", "シンプルなもののほうが好きです"],
    ["I prefer to decide later.", "あとで決めたいです"],
    ["I'm okay with either option.", "どちらでも大丈夫です"],
    ["Both options sound good.", "どちらもよさそうです"],
    ["That sounds more convenient.", "そのほうが便利そうです"],
    ["I'd like to keep my options open.", "選択肢を残しておきたいです"],
    ["I'm leaning toward the first one.", "最初の案に少し気持ちが傾いています"],
    ["Let's go with the easier plan.", "より簡単な案でいきましょう"],
    ["I don't have a strong preference.", "特に強いこだわりはありません"],
    ["I'm fine either way.", "どちらでもかまいません"],
    ["I'd like to compare them first.", "先に比べてみたいです"],
    ["That might be the better choice.", "それがよりよい選択かもしれません"],
    ["I want to think about it a little more.", "もう少し考えたいです"],
    ["Let's choose the safest option.", "いちばん安全な案を選びましょう"],
    ["I'm open to suggestions.", "提案を歓迎しています"],
    ["That's closer to what I want.", "それが自分の希望に近いです"]
  ], "希望や好みをやわらかく伝える実用フレーズです。断定しすぎず、自分の考えを自然に共有したいときに役立ちます。"),
  ...withSharedExplanation([
    ["I'm having trouble logging in.", "ログインに手こずっています"],
    ["My phone battery is low.", "スマホの充電が少ないです"],
    ["I can't find the right word.", "ぴったりの単語が出てきません"],
    ["I think I made a mistake.", "たぶん間違えました"],
    ["I may have the wrong address.", "住所が違うかもしれません"],
    ["Something doesn't seem right.", "何かおかしい気がします"],
    ["Could you take a look at this?", "これを見てもらえますか"],
    ["I need a hand with this.", "これを手伝ってほしいです"],
    ["I'm a little confused right now.", "今少し混乱しています"],
    ["I can't open this file.", "このファイルを開けません"],
    ["The app isn't working.", "アプリが動いていません"],
    ["I lost the message you sent.", "送ってもらったメッセージを見失いました"],
    ["I can't hear the audio clearly.", "音声がはっきり聞こえません"],
    ["I need help figuring this out.", "これを理解するのに助けが必要です"],
    ["Could you walk me through it?", "順を追って教えてもらえますか"],
    ["I need to fix this quickly.", "これを早く直す必要があります"],
    ["This part is confusing me.", "この部分で混乱しています"],
    ["I might need a backup plan.", "別案が必要になるかもしれません"]
  ], "困りごとや不具合を伝えるときのフレーズです。助けを求めながら状況を具体的に説明しやすくなります。"),
  ...withSharedExplanation([
    ["I see it a little differently.", "私は少し違う見方をしています"],
    ["That's a fair point.", "それはもっともな意見です"],
    ["I can understand that view.", "その考え方は理解できます"],
    ["I'd like to hear another opinion.", "別の意見も聞いてみたいです"],
    ["Let's compare the pros and cons.", "メリットとデメリットを比べましょう"],
    ["That seems reasonable to me.", "私にはもっともに思えます"],
    ["I'm not against it.", "それに反対ではありません"],
    ["I can support that idea.", "その案に賛成できます"],
    ["I have a slightly different suggestion.", "少し違う提案があります"],
    ["I think we're getting closer.", "だんだんまとまってきたと思います"],
    ["That may be too much for now.", "今は少しやりすぎかもしれません"],
    ["Let's not rush the decision.", "結論を急がないようにしましょう"],
    ["I'd rather keep things simple.", "できるだけシンプルにしたいです"],
    ["I think we should be careful.", "慎重に進めたほうがいいと思います"],
    ["That could work in some cases.", "場合によってはうまくいきそうです"],
    ["I'm interested in hearing more.", "もっと聞いてみたいです"],
    ["Let's come back to that idea.", "その案はあとでまた戻りましょう"]
  ], "意見交換や相談の場で使えるフレーズです。賛成、保留、慎重姿勢などを角が立ちにくい形で伝えられます。"),
  ...withSharedExplanation([
    ["I'm still building my vocabulary.", "まだ語彙を増やしている途中です"],
    ["I'm trying to sound more natural.", "もっと自然に話せるようにしています"],
    ["Please correct me if I'm wrong.", "間違っていたら直してください"],
    ["I'm not sure if this phrase is natural.", "この表現が自然か少し自信がありません"],
    ["How would a native speaker say this?", "ネイティブならどう言いますか"],
    ["I know the word, but I can't use it well yet.", "単語は知っていますが、まだうまく使えません"],
    ["I'm trying to think in English.", "英語で考えるようにしています"],
    ["I need more speaking practice.", "もっとスピーキング練習が必要です"],
    ["I want to improve my listening.", "リスニング力を上げたいです"],
    ["That phrase is easy to remember.", "その表現は覚えやすいです"],
    ["I hear this expression a lot.", "この表現はよく耳にします"],
    ["I've seen this word before.", "この単語は前に見たことがあります"],
    ["I want to use this in a sentence.", "これを文の中で使ってみたいです"],
    ["Could you check my pronunciation?", "発音を確認してもらえますか"],
    ["This expression is new to me.", "この表現は初めてです"],
    ["I'm getting used to it little by little.", "少しずつ慣れてきています"],
    ["I want to sound more confident.", "もっと自信を持って話せるようになりたいです"],
    ["I'm starting to understand the pattern.", "パターンが少しずつわかってきました"]
  ], "英語学習そのものについて話すときの実用フレーズです。学び方や苦手ポイントを英語で共有したい場面に向いています。"),
  ...withSharedExplanation([
    ["Could you hold this for a moment?", "これを少し持っていてもらえますか"],
    ["Could you wrap this separately?", "これを別で包んでもらえますか"],
    ["I'd like to return this item.", "この商品を返品したいです"],
    ["I'd like to exchange this for another one.", "これを別のものに交換したいです"],
    ["Could you check the price again?", "もう一度値段を確認してもらえますか"],
    ["Is there a discount on this?", "これは割引になりますか"],
    ["Can you put this on hold?", "これを取り置きできますか"],
    ["I only need one of these.", "これは一つだけで大丈夫です"],
    ["Could you pack it carefully?", "丁寧に包んでもらえますか"],
    ["I'll come back for it later.", "あとで取りに戻ります"],
    ["Could you recommend the most popular one?", "いちばん人気のものを教えてもらえますか"],
    ["Is there anything cheaper?", "もっと安いものはありますか"],
    ["Is there anything easier to use?", "もっと使いやすいものはありますか"],
    ["I'd like something for everyday use.", "普段使いできるものが欲しいです"],
    ["Could you show me the difference?", "違いを見せてもらえますか"],
    ["I need one that works well.", "ちゃんと使いやすいものが必要です"],
    ["This one fits my needs.", "これは自分の用途に合っています"],
    ["I just need the basics.", "基本的なもので十分です"]
  ], "買い物や手続きで少し踏み込んだ相談をしたいときのフレーズです。比較、返品、取り置きなど実用度の高い内容をまとめています。"),
  ...withSharedExplanation([
    ["Please let me know when you're free.", "空いたら教えてください"],
    ["Send me your location when you arrive.", "着いたら位置情報を送ってください"],
    ["I'll wait near the entrance.", "入口の近くで待っています"],
    ["I'll be there in about ten minutes.", "10分くらいで着きます"],
    ["Please text me when you get home.", "家に着いたらメッセージしてください"],
    ["I may be offline for a while.", "しばらく連絡が取りにくいかもしれません"],
    ["I'll call you after dinner.", "夕食のあとに電話します"],
    ["Let's check the weather first.", "まず天気を確認しましょう"],
    ["I'll bring what we need.", "必要なものはこちらで持っていきます"],
    ["Don't worry, I have a backup.", "心配しないでください、予備があります"],
    ["Let's make a simple checklist.", "簡単なチェックリストを作りましょう"],
    ["I only need a quick answer.", "短い返事だけで大丈夫です"],
    ["I'll send you an update later.", "あとで最新状況を送ります"],
    ["We can sort it out together.", "一緒に整理していけます"],
    ["Let's do one thing at a time.", "一つずつ進めましょう"],
    ["I'll handle this part first.", "まずこの部分を進めます"],
    ["Tell me what works best for you.", "あなたにとって都合のよい方法を教えてください"]
  ], "連絡の取り方や段取りを整えるときのフレーズです。待ち合わせ、共有、分担など日常の実務で広く使えます。")
];

const businessPhraseExpansion = [
  ...withSharedExplanation([
    ["Let's start the meeting.", "会議を始めましょう"],
    ["Let's stick to the agenda.", "議題に沿って進めましょう"],
    ["We'll begin in a minute.", "まもなく始めます"],
    ["Thanks everyone for joining.", "ご参加ありがとうございます"],
    ["Could you turn on your camera?", "カメラをオンにしてもらえますか"],
    ["Could you mute yourself?", "ミュートにしてもらえますか"],
    ["Can you see my screen?", "こちらの画面は見えていますか"],
    ["I'll share my screen now.", "今から画面共有します"],
    ["Let's save questions for the end.", "質問は最後にまとめましょう"],
    ["We have about ten minutes left.", "残りはあと10分ほどです"],
    ["Let's hear from the sales team.", "営業チームの話を聞きましょう"],
    ["Could you walk us through the slide?", "このスライドを説明してもらえますか"],
    ["Let's move to the next topic.", "次の話題に移りましょう"],
    ["I'd like to revisit the last point.", "さきほどの点に戻りたいです"],
    ["Can we summarize the action items?", "対応事項を整理できますか"],
    ["Let's end on time.", "予定どおりに終えましょう"],
    ["We'll take a short break.", "短い休憩を取りましょう"],
    ["Could you speak to that point?", "その点について話してもらえますか"],
    ["Let's keep this meeting focused.", "この会議は要点を絞って進めましょう"],
    ["I'll send the notes afterward.", "あとでメモを送ります"]
  ], "会議の進行でそのまま使いやすいビジネスフレーズです。開始、共有、質疑応答、締めの流れを自然に作れます。"),
  ...withSharedExplanation([
    ["We need to update the schedule.", "スケジュールを更新する必要があります"],
    ["The timeline is getting tight.", "日程がかなり厳しくなってきています"],
    ["We may need extra support.", "追加の支援が必要かもしれません"],
    ["Let's break the task into smaller steps.", "作業を小さな工程に分けましょう"],
    ["We should set a clear owner.", "担当者を明確にしたほうがよいです"],
    ["I'll take care of the first draft.", "最初の案は私が担当します"],
    ["Can you handle the next step?", "次の工程を担当できますか"],
    ["We need a better estimate.", "もっと精度の高い見積もりが必要です"],
    ["Let's review the scope again.", "対応範囲をもう一度確認しましょう"],
    ["The priority has changed.", "優先順位が変わりました"],
    ["We should avoid last-minute changes.", "直前の変更は避けたほうがよいです"],
    ["Let's keep the process simple.", "進め方はシンプルにしましょう"],
    ["We need to unblock this task.", "この作業の詰まりを解消する必要があります"],
    ["I'm waiting on the final approval.", "最終承認を待っています"],
    ["We can start once the budget is confirmed.", "予算が確定したら開始できます"],
    ["Let's aim to finish by Friday.", "金曜までの完了を目指しましょう"],
    ["We should leave room for testing.", "テストの時間も確保しましょう"],
    ["I'll draft a revised plan.", "修正版の計画を作成します"],
    ["We need a more realistic target.", "もっと現実的な目標が必要です"],
    ["Let's flag any blockers early.", "問題は早めに共有しましょう"]
  ], "計画、進行管理、優先順位づけで使えるフレーズです。プロジェクトを前に進める会話で特に出番が多い表現です。"),
  ...withSharedExplanation([
    ["Please review the attached file.", "添付ファイルを確認してください"],
    ["I've attached the latest version.", "最新版を添付しました"],
    ["Could you send me the editable file?", "編集できるファイルを送ってもらえますか"],
    ["Please use the new template.", "新しいテンプレートを使ってください"],
    ["I updated the document this morning.", "今朝この資料を更新しました"],
    ["The link should work now.", "今はリンクが使えるはずです"],
    ["I'll resend the file shortly.", "すぐにファイルを再送します"],
    ["Please check the numbers on page two.", "2ページ目の数字を確認してください"],
    ["Could you merge these comments?", "これらのコメントを反映してもらえますか"],
    ["I left a note in the document.", "資料にメモを残しました"],
    ["Let's keep version names consistent.", "版の名前は統一しましょう"],
    ["I'll clean up the formatting.", "書式を整えます"],
    ["Could you proofread this message?", "このメッセージを確認してもらえますか"],
    ["Please confirm receipt.", "受領確認をお願いします"],
    ["I need the signed copy.", "署名済みの控えが必要です"],
    ["The spreadsheet has been updated.", "表は更新済みです"],
    ["I'll share the folder access.", "フォルダのアクセス権を共有します"],
    ["Please upload the final file here.", "最終ファイルをここにアップロードしてください"],
    ["Could you rename this file clearly?", "このファイル名をわかりやすく変更してもらえますか"],
    ["Let's keep all documents in one place.", "資料は一か所にまとめましょう"]
  ], "メール、資料、ファイル共有で役立つビジネスフレーズです。ドキュメントまわりのやり取りを英語で進めやすくなります。"),
  ...withSharedExplanation([
    ["Can you take ownership of this?", "これを担当してもらえますか"],
    ["I'd appreciate your input on this.", "これについて意見をもらえると助かります"],
    ["Let's sync up after lunch.", "昼食後に認識を合わせましょう"],
    ["Please loop me in on that thread.", "そのやり取りに私も入れてください"],
    ["We need better coordination across teams.", "チーム間の連携をもっと良くする必要があります"],
    ["I'll reach out to design.", "デザインチームに連絡します"],
    ["Let's align on the next steps.", "次の進め方をそろえましょう"],
    ["Could you support us on this item?", "この件でサポートしてもらえますか"],
    ["We should divide the work more clearly.", "作業分担をもっと明確にしましょう"],
    ["Let's avoid duplicating effort.", "二重作業は避けましょう"],
    ["Please keep everyone in the loop.", "全員に状況共有をお願いします"],
    ["I'll coordinate with the vendor.", "取引先と調整します"],
    ["We need a quick handoff.", "すばやい引き継ぎが必要です"],
    ["Let's confirm who is doing what.", "誰が何をするか確認しましょう"],
    ["Could you cover for me this afternoon?", "今日の午後、代わりに対応してもらえますか"],
    ["I'll step in if needed.", "必要なら私が入ります"],
    ["Let's keep communication transparent.", "情報共有はオープンに進めましょう"],
    ["We should document that decision.", "その決定は記録に残したほうがよいです"],
    ["I'll check with the operations team.", "運用チームに確認します"],
    ["Please share any concerns early.", "懸念点は早めに共有してください"]
  ], "チーム内の連携や役割分担に使えるフレーズです。協力依頼や調整を英語で自然に進めたいときに向いています。"),
  ...withSharedExplanation([
    ["Could you send the quote by today?", "見積もりを今日中に送ってもらえますか"],
    ["Please update the client before noon.", "正午までに顧客へ連絡してください"],
    ["Let's respond by end of day.", "本日中に返答しましょう"],
    ["I need a quick approval on this.", "これを早めに承認してほしいです"],
    ["Could you prioritize this request?", "この依頼を優先してもらえますか"],
    ["Please confirm the meeting room.", "会議室の確認をお願いします"],
    ["Can you arrange a call with them?", "先方との通話を設定できますか"],
    ["I'd like to propose a simpler option.", "もっとシンプルな案を提案したいです"],
    ["Please prepare a customer-facing version.", "顧客向けの版を用意してください"],
    ["We should keep the message concise.", "メッセージは簡潔にしましょう"],
    ["Could you tailor this for the client?", "これを顧客向けに調整してもらえますか"],
    ["Let's avoid overpromising here.", "ここでは言いすぎないようにしましょう"],
    ["I need your sign-off before we proceed.", "進める前に承認が必要です"],
    ["Please make this easier to understand.", "もっとわかりやすくしてください"],
    ["Could you send a polite reminder?", "丁寧なリマインドを送ってもらえますか"],
    ["We need to manage expectations carefully.", "期待値の調整を丁寧に行う必要があります"],
    ["Let's prepare for follow-up questions.", "追加質問に備えましょう"],
    ["Please confirm what the client needs.", "顧客が必要としていることを確認してください"],
    ["I'd like to keep this professional but warm.", "丁寧さを保ちつつ柔らかい文面にしたいです"],
    ["Could you draft the response for me?", "返答文のたたき台を作ってもらえますか"]
  ], "顧客対応や外向け連絡で使えるフレーズです。依頼、確認、文面調整など実務でそのまま活かしやすい表現をそろえています。"),
  ...withSharedExplanation([
    ["Sales were stronger than expected.", "売上は予想より好調でした"],
    ["Costs came in slightly higher.", "コストは少し高めに着地しました"],
    ["We're seeing a delay in shipping.", "出荷に遅れが出ています"],
    ["There's a risk of confusion here.", "ここは混乱が起きるおそれがあります"],
    ["The current plan has a gap.", "現在の計画には抜けがあります"],
    ["We found an issue in testing.", "テストで問題が見つかりました"],
    ["The numbers don't match yet.", "まだ数字が合っていません"],
    ["We need to escalate this quickly.", "これを早急に上げる必要があります"],
    ["The rollout is behind schedule.", "展開が予定より遅れています"],
    ["Customer feedback has been positive.", "顧客の反応は好意的です"],
    ["We've identified the root cause.", "根本原因は特定できました"],
    ["The system was down for about an hour.", "システムは約1時間停止していました"],
    ["We're monitoring the situation closely.", "状況を注意深く見ています"],
    ["I want to raise one concern.", "一つ懸念点を共有したいです"],
    ["We need to fix this before launch.", "公開前にこれを直す必要があります"],
    ["The latest update caused a problem.", "最新の更新で問題が起きました"],
    ["This could affect the deadline.", "これは締切に影響する可能性があります"],
    ["The team is working on a solution.", "チームで解決策に取り組んでいます"],
    ["We're still gathering the facts.", "まだ事実確認を進めているところです"],
    ["I'll share the findings once they're ready.", "まとまり次第、結果を共有します"]
  ], "状況報告や問題共有の場面で使えるフレーズです。数字、遅延、原因、対応方針を簡潔に伝える練習に向いています。"),
  ...withSharedExplanation([
    ["Could we revisit the price?", "価格をもう一度見直せますか"],
    ["Is there any flexibility on the deadline?", "締切には多少の調整余地がありますか"],
    ["We'd like to reduce the scope a little.", "範囲を少し絞りたいです"],
    ["That option may be outside our budget.", "その案は予算外かもしれません"],
    ["We'd prefer a shorter contract term.", "契約期間は短めを希望します"],
    ["Could you clarify the terms?", "条件を明確にしてもらえますか"],
    ["Let's find a middle ground.", "落としどころを探しましょう"],
    ["We need to compare both proposals.", "両方の提案を比較する必要があります"],
    ["I'd like some time to review this internally.", "社内で確認する時間をいただきたいです"],
    ["That seems reasonable from our side.", "こちらとしては妥当だと思います"],
    ["We can move forward with that condition.", "その条件なら進められます"],
    ["Let's keep the first phase small.", "最初の段階は小さく始めましょう"],
    ["I'd rather not commit to that yet.", "それにはまだ約束したくありません"],
    ["We need clearer success metrics.", "成功基準をもっと明確にする必要があります"],
    ["Could we test this first?", "まず試せますか"],
    ["Let's make a decision by tomorrow.", "明日までに決めましょう"],
    ["I want to be careful with this commitment.", "この約束は慎重に扱いたいです"],
    ["That sounds workable to us.", "こちらとしては現実的に進められそうです"],
    ["We should confirm the details in writing.", "詳細は書面で確認したほうがよいです"],
    ["Let's proceed step by step.", "段階的に進めましょう"]
  ], "交渉や意思決定の場で使えるビジネスフレーズです。条件確認、保留、妥協点の提案などを丁寧に表現できます。"),
  ...withSharedExplanation([
    ["I'll follow up tomorrow morning.", "明日の朝に追って確認します"],
    ["Please mark this as complete.", "これを完了として扱ってください"],
    ["Let's close this out today.", "この件は今日中に締めましょう"],
    ["Could you send a quick reminder?", "簡単なリマインドを送ってもらえますか"],
    ["I'll keep an eye on it.", "引き続き確認しておきます"],
    ["Please update the tracker.", "進捗表を更新してください"],
    ["We need a smoother handoff next time.", "次回はもっとスムーズに引き継ぐ必要があります"],
    ["Let's create a simple checklist.", "簡単なチェックリストを作りましょう"],
    ["I'll confirm once it's done.", "終わったら確認します"],
    ["Please note the change in the system.", "システム上の変更を記録してください"],
    ["We should automate this later.", "これは後で自動化したほうがよいです"],
    ["Let's reduce manual work here.", "ここは手作業を減らしましょう"],
    ["Could you check the status again?", "もう一度状況を確認してもらえますか"],
    ["I'll send a follow-up email.", "フォローアップのメールを送ります"],
    ["We need to keep this moving.", "この件は止めずに進める必要があります"],
    ["Please escalate if needed.", "必要ならエスカレーションしてください"],
    ["Let's review what worked well.", "うまくいった点を振り返りましょう"],
    ["We should improve the process next time.", "次回は進め方を改善しましょう"],
    ["I'll capture the lessons learned.", "学びをまとめておきます"],
    ["Thanks for turning this around quickly.", "すばやく対応してくれてありがとうございます"]
  ], "対応後のフォロー、運用改善、締め作業に使えるフレーズです。日々の業務を回す会話でそのまま使いやすい表現です。")
];

const travelPhraseExpansion = [
  ...withSharedExplanation([
    ["Where is the check-in counter?", "チェックインカウンターはどこですか"],
    ["Which line is for international flights?", "国際線はどの列ですか"],
    ["Could you help me with this kiosk?", "この端末の操作を手伝ってもらえますか"],
    ["I need to check this bag.", "この荷物を預けたいです"],
    ["Can I carry this on board?", "これは機内に持ち込めますか"],
    ["Is this the line for security?", "これは保安検査の列ですか"],
    ["How early should I be at the gate?", "何分前に搭乗口へ行けばいいですか"],
    ["Has boarding started yet?", "もう搭乗は始まりましたか"],
    ["Which zone is boarding now?", "今はどのグループが搭乗していますか"],
    ["Could you print my boarding pass?", "搭乗券を印刷してもらえますか"],
    ["I think I'm at the wrong terminal.", "ターミナルを間違えた気がします"],
    ["How do I get to Terminal 2?", "第2ターミナルへはどう行けばいいですか"],
    ["Is my flight on time?", "私の便は定刻ですか"],
    ["Has the gate changed?", "搭乗口は変更になりましたか"],
    ["Where can I refill my water bottle?", "水筒に水を入れられる場所はどこですか"],
    ["Do I need to remove my laptop?", "ノートパソコンは出す必要がありますか"],
    ["Can I keep my shoes on?", "靴は履いたままで大丈夫ですか"],
    ["Where is passport control?", "入国審査はどこですか"],
    ["I have a short connection.", "乗り継ぎ時間が短いです"],
    ["Could you tell me where baggage claim is?", "手荷物受取所はどこか教えてもらえますか"]
  ], "空港や搭乗手続きでそのまま役立つ旅行フレーズです。出発前後の不安を減らしやすい実用表現を集めています。"),
  ...withSharedExplanation([
    ["Could you store my bags until check-in?", "チェックインまで荷物を預かってもらえますか"],
    ["Is my room ready yet?", "部屋の準備はできていますか"],
    ["Could I see the room first?", "先に部屋を見てもいいですか"],
    ["I'd prefer a quiet room.", "静かな部屋を希望します"],
    ["Is there an elevator nearby?", "近くにエレベーターはありますか"],
    ["Could you call a taxi for me?", "タクシーを呼んでもらえますか"],
    ["What floor is the breakfast room on?", "朝食会場は何階ですか"],
    ["Is housekeeping available now?", "今、清掃をお願いできますか"],
    ["The shower has no hot water.", "シャワーのお湯が出ません"],
    ["Could you send someone up?", "部屋に来てもらえますか"],
    ["I think the key card isn't working.", "カードキーが使えないようです"],
    ["Is there a laundry room here?", "ここにランドリールームはありますか"],
    ["Can I borrow an adapter?", "変換プラグを借りられますか"],
    ["What time does breakfast start?", "朝食は何時からですか"],
    ["Could I get an extra blanket?", "毛布をもう一枚もらえますか"],
    ["The room is too cold.", "部屋が寒すぎます"],
    ["The room is too noisy.", "部屋がうるさすぎます"],
    ["Can I pay at check-out?", "支払いはチェックアウト時でいいですか"],
    ["Could you book an airport shuttle for me?", "空港シャトルを予約してもらえますか"]
  ], "ホテルでのチェックイン前後や設備相談に使える旅行フレーズです。宿泊中の困りごとにもすぐ対応しやすくなります。"),
  ...withSharedExplanation([
    ["Do you have an English menu?", "英語のメニューはありますか"],
    ["What's the soup of the day?", "本日のスープは何ですか"],
    ["Could we sit outside?", "外の席に座れますか"],
    ["Could I get another plate?", "取り皿をもう一枚もらえますか"],
    ["This isn't what I ordered.", "これは注文したものと違います"],
    ["Could you make it less sweet?", "甘さを控えめにできますか"],
    ["I'd like the bill, please.", "お会計をお願いします"],
    ["Can we pay separately?", "別々に払えますか"],
    ["Is service included?", "サービス料は含まれていますか"],
    ["What do you recommend for dessert?", "デザートのおすすめは何ですか"],
    ["I'd like something local.", "地元らしいものを食べたいです"],
    ["Could I have more napkins?", "ナプキンをもう少しもらえますか"],
    ["Is there a vegetarian option?", "ベジタリアン向けの選択肢はありますか"],
    ["Is this dish spicy?", "この料理は辛いですか"],
    ["Can you make it mild?", "辛さを控えめにできますか"],
    ["I'd like my steak well done.", "ステーキはよく焼きでお願いします"],
    ["Could I have a fork and spoon?", "フォークとスプーンをもらえますか"],
    ["Could you pack the leftovers?", "残りを持ち帰り用に包んでもらえますか"],
    ["Can I pay by card here?", "ここではカードで払えますか"]
  ], "飲食店やカフェでそのまま使える旅行フレーズです。注文、席、会計、食事制限の相談まで幅広くカバーしています。"),
  ...withSharedExplanation([
    ["Which platform do I need?", "どのホームに行けばいいですか"],
    ["Does this train stop there?", "この電車はそこに止まりますか"],
    ["How many stops is it from here?", "ここから何駅ですか"],
    ["Should I transfer at the next station?", "次の駅で乗り換えるべきですか"],
    ["Is this the last train tonight?", "今夜の終電ですか"],
    ["Where do I buy a ticket?", "切符はどこで買えますか"],
    ["Can I use a card for the fare?", "運賃の支払いにカードは使えますか"],
    ["How often does this bus run?", "このバスはどれくらいの間隔で来ますか"],
    ["Which side should I get on?", "どちら側から乗ればいいですか"],
    ["Is this seat reserved?", "この席は指定席ですか"],
    ["Could you tell me when to get off?", "降りる場所になったら教えてもらえますか"],
    ["I missed my stop.", "降りる場所を過ぎてしまいました"],
    ["How do I get back to downtown?", "中心街へ戻るにはどう行けばいいですか"],
    ["Is there a direct train?", "直通電車はありますか"],
    ["Does this bus go near the museum?", "このバスは博物館の近くを通りますか"],
    ["Which exit should I use?", "どの出口を使えばいいですか"],
    ["Can I top up this transit card here?", "ここで交通系カードにチャージできますか"],
    ["Is the station within walking distance?", "駅までは歩ける距離ですか"],
    ["How long is the ride?", "所要時間はどれくらいですか"],
    ["Is there a faster route?", "もっと早い行き方はありますか"]
  ], "電車やバスでの移動に役立つ旅行フレーズです。乗り場、乗り換え、時間、支払いをまとめて確認しやすくなります。"),
  ...withSharedExplanation([
    ["I'm just looking, thanks.", "見ているだけです、ありがとう"],
    ["Do you have this in black?", "これの黒はありますか"],
    ["Could you show me a cheaper one?", "もっと安いものを見せてもらえますか"],
    ["Is tax included in the price?", "税金はこの値段に含まれていますか"],
    ["Can I pay in cash?", "現金で払えますか"],
    ["Do you accept contactless payment?", "タッチ決済は使えますか"],
    ["Could I get a receipt?", "レシートをもらえますか"],
    ["Is there a fitting room?", "試着室はありますか"],
    ["This doesn't fit me well.", "これはあまり合いません"],
    ["Do you have this in stock?", "これは在庫がありますか"],
    ["Could you hold this for a while?", "これを少し取り置きできますか"],
    ["Is there a warranty on this?", "これには保証がありますか"],
    ["Can I open the box?", "箱を開けてもいいですか"],
    ["I'd like to buy two of these.", "これを二つ買いたいです"],
    ["Could you gift-wrap this?", "プレゼント用に包んでもらえますか"],
    ["Is there a local brand you recommend?", "おすすめの地元ブランドはありますか"],
    ["Which one sells best?", "いちばん売れているのはどれですか"],
    ["Can I try the sample?", "試供品を試せますか"],
    ["Do you have anything lighter?", "もっと軽いものはありますか"],
    ["Could you pack this in my suitcase?", "これをスーツケースに入れやすく包んでもらえますか"]
  ], "旅先での買い物に便利なフレーズです。色違い、在庫、保証、支払いなどを英語で確認したいときに役立ちます。"),
  ...withSharedExplanation([
    ["Is there a guided tour today?", "今日はガイドツアーがありますか"],
    ["How long does the tour last?", "ツアーはどれくらいの長さですか"],
    ["Where do we meet the guide?", "ガイドとはどこで集合しますか"],
    ["Is photography allowed inside?", "中で写真を撮ってもいいですか"],
    ["What's the best time to visit?", "行くならいつがいちばんよいですか"],
    ["Is there a student discount?", "学生割引はありますか"],
    ["Can I buy tickets online?", "チケットはオンラインで買えますか"],
    ["Is there a line for prepaid tickets?", "事前購入チケット用の列はありますか"],
    ["Where is the entrance to the temple?", "お寺の入口はどこですか"],
    ["Are there lockers nearby?", "近くにロッカーはありますか"],
    ["Is this trail easy to walk?", "この道は歩きやすいですか"],
    ["How far is the viewpoint?", "展望スポットまではどれくらいですか"],
    ["Could you recommend another place nearby?", "この近くで別のおすすめ場所はありますか"],
    ["What's this building called?", "この建物は何という名前ですか"],
    ["Is this area crowded on weekends?", "このあたりは週末に混みますか"],
    ["Can I walk there from here?", "ここから歩いて行けますか"],
    ["Is there a restroom nearby?", "近くにトイレはありますか"],
    ["Which attraction should I see first?", "最初に見るならどれがおすすめですか"]
  ], "観光地や施設で役立つ旅行フレーズです。見学ルートやおすすめを尋ねながら、快適に観光しやすくなります。"),
  ...withSharedExplanation([
    ["I think I lost my wallet.", "財布をなくしたかもしれません"],
    ["My bag is missing.", "かばんが見当たりません"],
    ["I need to report a lost item.", "遺失物の届けを出したいです"],
    ["I need a pharmacy.", "薬局が必要です"],
    ["Do you sell pain medicine?", "痛み止めはありますか"],
    ["I have a fever.", "熱があります"],
    ["My stomach hurts.", "お腹が痛いです"],
    ["Is there a hospital nearby?", "近くに病院はありますか"],
    ["I think I twisted my ankle.", "足首をひねったようです"],
    ["Could you help me call my hotel?", "ホテルに電話するのを手伝ってもらえますか"],
    ["My phone won't charge.", "スマホが充電できません"],
    ["I dropped my passport somewhere.", "どこかでパスポートを落としました"],
    ["What should I do now?", "今どうすればいいですか"],
    ["I need emergency help.", "緊急の助けが必要です"],
    ["I don't feel well.", "体調がよくありません"],
    ["I need a place to sit down.", "座れる場所が必要です"],
    ["Can I use your phone for a moment?", "少しだけ電話を借りてもいいですか"],
    ["I need to contact my family.", "家族に連絡する必要があります"]
  ], "トラブルや体調不良のときに役立つ旅行フレーズです。緊急時でも落ち着いて必要なことを伝えやすくなります。"),
  ...withSharedExplanation([
    ["Where can I exchange money?", "両替はどこでできますか"],
    ["What's the exchange rate today?", "今日のレートはいくらですか"],
    ["Can I use foreign cards here?", "海外のカードは使えますか"],
    ["Could you break this bill?", "このお札をくずせますか"],
    ["Do I need exact change?", "ちょうどの金額が必要ですか"],
    ["Is there a plug I can use?", "使えるコンセントはありますか"],
    ["Does the room have USB ports?", "部屋にUSBポートはありますか"],
    ["Can I connect to the airport Wi-Fi?", "空港のWi-Fiに接続できますか"],
    ["Is the connection stable here?", "ここは通信が安定していますか"],
    ["Could you help me set up the SIM card?", "SIMカードの設定を手伝ってもらえますか"],
    ["How much data does this plan include?", "このプランには何GB入っていますか"],
    ["Is roaming cheaper than buying a SIM?", "ローミングのほうがSIMを買うより安いですか"],
    ["Where can I charge this power bank?", "このモバイルバッテリーはどこで充電できますか"],
    ["Can I buy a ticket with my phone?", "スマホでチケットを買えますか"],
    ["Does this machine take coins?", "この機械はコインに対応していますか"],
    ["Could you show me how this works?", "使い方を見せてもらえますか"],
    ["Is there a service fee?", "手数料はかかりますか"],
    ["Can I leave a tip by card?", "チップはカードで払えますか"],
    ["Can I get cash back here?", "ここでキャッシュバックはできますか"]
  ], "お金、通信、充電まわりで役立つ旅行フレーズです。現地で困りやすい支払いとネット接続の場面をまとめて練習できます。")
];

const practicalPhraseBoost = {
  basic: [
    ["Can you help me for a minute?", "ちょっと手伝ってもらえますか", "短い時間だけ手伝ってほしいときの自然な頼み方です。help は「助ける」だけでなく、日常では「手伝う」の意味でよく使います。"],
    ["I need some help with this.", "これをちょっと手伝ってほしいです", "困っている内容を this で指しながら、相手に手伝いをお願いする表現です。"],
    ["Do you have a minute?", "少し時間ありますか", "相手に短く話す時間があるか確認する表現です。minute は文字通り1分だけでなく「少しの時間」の意味でも使います。"],
    ["Just a minute, please.", "少しだけ待ってください", "相手を待たせるときの短い一言です。電話や店頭、作業中の返事として使いやすいです。"],
    ["Can I ask you something?", "少し聞いてもいいですか", "質問に入る前のやわらかい前置きです。いきなり質問するより自然に聞こえます。"],
    ["Could you say that again slowly?", "もう一度ゆっくり言ってもらえますか", "聞き取れなかったときに、速度も落としてほしいと伝えられる表現です。"],
    ["What should I do next?", "次に何をすればいいですか", "手順が分からないときに次の行動を確認できます。仕事、学校、旅行先でも便利です。"],
    ["I made a mistake.", "間違えました", "自分のミスを短く伝える基本表現です。続けて Can I try again? と言うと自然です。"],
    ["Can I try again?", "もう一度やってもいいですか", "失敗したあとに再挑戦したいときの表現です。練習や手続きで使いやすいです。"],
    ["Please show me one more time.", "もう一度見せてください", "説明を見本で確認したいときの表現です。show me は「見せながら教える」場面にも合います。"],
    ["I'm not sure yet.", "まだはっきり分かりません", "即答できないときに、断定を避けて自然に返せる一言です。"],
    ["That helps a lot.", "とても助かります", "相手の説明や手助けに感謝を伝える表現です。Thank you. に続けると自然です。"],
    ["I have a small problem.", "少し困っています", "大きなトラブルではないけれど助けが必要なときに使えます。"],
    ["Can you check this for me?", "これを確認してもらえますか", "書類、画面、答えなどを相手に見てもらいたいときの表現です。"],
    ["I don't understand this part.", "この部分が分かりません", "分からない場所を this part で絞って伝える実用表現です。"],
    ["Where should I put this?", "これはどこに置けばいいですか", "片付けや荷物の受け渡しで使いやすい質問です。"],
    ["Can I have a little more?", "もう少しもらえますか", "飲み物、時間、説明などを少し追加してほしいときに応用できます。"],
    ["This is enough for now.", "今はこれで十分です", "追加が不要なことをやわらかく伝えられる表現です。"],
    ["Let's do it together.", "一緒にやりましょう", "相手と一緒に行動したいときの前向きな表現です。"],
    ["I'll try my best.", "できるだけ頑張ります", "完璧を約束せず、前向きに取り組む気持ちを伝えられます。"]
  ],
  practical: [
    ["Could you help me figure this out?", "これを一緒に考えてもらえますか", "答えがすぐ出ない問題について、相手に相談したいときの自然な表現です。"],
    ["I need to think about it for a minute.", "少し考えさせてください", "即答を避けて短い時間をもらいたいときに使えます。for a minute は「少しの間」の意味です。"],
    ["Let me check one thing first.", "先に一つ確認させてください", "話を進める前に重要な点を確認したいときの表現です。"],
    ["Could you be more specific?", "もう少し具体的に言ってもらえますか", "説明が広すぎるときに、内容を絞ってもらうための実用表現です。"],
    ["What exactly do you mean?", "具体的にはどういう意味ですか", "相手の意図をもう少し正確に確認したいときの表現です。"],
    ["That sounds a bit different from what I expected.", "思っていたものと少し違うようです", "期待と違うことを強く否定せずに伝えられます。"],
    ["Can we look at another option?", "別の選択肢も見られますか", "一つの案に決めず、他の可能性を確認したいときに使えます。"],
    ["I'm leaning toward this one.", "どちらかというとこちらにしたいです", "完全には決めていないが、気持ちが傾いていることを表せます。"],
    ["Let's compare the pros and cons.", "良い点と悪い点を比べましょう", "判断材料を整理したいときの定番表現です。"],
    ["I want to avoid any confusion.", "誤解がないようにしたいです", "確認や言い直しを丁寧に行いたいときに使えます。"],
    ["Could you explain the difference?", "違いを説明してもらえますか", "似ている選択肢や単語の違いを知りたいときに便利です。"],
    ["That makes sense now.", "今ので納得できました", "説明を聞いて理解できたことを自然に伝えられます。"],
    ["I may have misunderstood.", "私が誤解していたかもしれません", "相手を責めずに、自分側の理解違いとして修正できます。"],
    ["Can we start with the basics?", "基本から始めてもいいですか", "難しい話に入る前に土台から確認したいときの表現です。"],
    ["I want to practice this out loud.", "これを声に出して練習したいです", "英語学習や発音練習でそのまま使える一言です。"],
    ["Could you correct my sentence?", "私の文を直してもらえますか", "英作文や会話練習で、相手に添削を頼む表現です。"],
    ["Is this phrase natural?", "この表現は自然ですか", "直訳っぽくないか確認したいときに非常に実用的です。"],
    ["What's a more casual way to say this?", "もっとカジュアルな言い方はありますか", "硬い表現を自然な会話表現に変えたいときに使えます。"],
    ["Can you give me a real-life example?", "実際の場面での例を出してもらえますか", "机上の説明ではなく、日常で使う形を知りたいときの表現です。"],
    ["Let's use a simpler sentence.", "もっと簡単な文を使いましょう", "複雑な文を避けて分かりやすく伝えたいときに便利です。"]
  ],
  business: [
    ["Could you give me a brief update?", "簡単に進捗を教えてもらえますか", "長い説明ではなく、要点だけを確認したいときのビジネス表現です。"],
    ["Let's handle this case by case.", "これは一件ずつ対応しましょう", "状況によって対応が変わるときに、まとめて決めない方針を伝えます。"],
    ["Please keep me in the loop.", "私にも情報共有をお願いします", "進捗や変更があったときに自分も共有先に入れてほしいと伝える表現です。"],
    ["Can we make the next step clear?", "次にやることを明確にできますか", "会議後に行動が曖昧にならないよう確認する表現です。"],
    ["Who is responsible for this task?", "この作業の担当者は誰ですか", "責任者や担当を明確にしたいときの実務表現です。"],
    ["Let's confirm the scope before we start.", "始める前に対応範囲を確認しましょう", "作業の範囲違いを防ぐために使える表現です。"],
    ["Could you share the latest version?", "最新版を共有してもらえますか", "資料やファイルの更新版を確認したいときに使います。"],
    ["I'll send a short recap after this.", "このあと簡単なまとめを送ります", "会議や相談の内容を後で整理して共有すると伝える表現です。"],
    ["Let's not decide this too quickly.", "これは急いで決めすぎないようにしましょう", "重要な判断を慎重に進めたいときのやわらかい表現です。"],
    ["Could you flag any concerns?", "懸念点があれば共有してもらえますか", "問題になりそうな点を事前に出してほしいときに使えます。"],
    ["We need to align on the details.", "詳細の認識をそろえる必要があります", "細かな条件のずれを防ぐためのビジネス頻出表現です。"],
    ["Let's keep the message simple.", "伝える内容はシンプルにしましょう", "説明や資料を分かりやすくまとめたいときに使えます。"],
    ["Could you review this before noon?", "正午までにこれを確認してもらえますか", "期限つきで確認を依頼する実用的な表現です。"],
    ["I need approval before moving forward.", "進める前に承認が必要です", "勝手に進められない理由を自然に説明できます。"],
    ["Let's prepare a backup plan.", "代替案を用意しましょう", "予定通りに進まない場合に備える表現です。"],
    ["Can we reduce the risk here?", "ここのリスクを下げられますか", "懸念点に対して改善策を考えたいときに使えます。"],
    ["The main issue is the timing.", "主な問題はタイミングです", "論点を絞って説明するときに便利な表現です。"],
    ["Let's revisit this once we have more data.", "もう少しデータがそろってから再検討しましょう", "判断材料が不足しているため保留にしたいときに使えます。"],
    ["Could you summarize the decision?", "決定事項をまとめてもらえますか", "会議の最後に合意内容を確認する表現です。"],
    ["I'll follow up if anything changes.", "変更があれば追加で連絡します", "状況が動いたときに連絡すると伝える締めの表現です。"]
  ],
  travel: [
    ["Could you help me read this sign?", "この表示を読むのを手伝ってもらえますか", "標識や案内表示が分からないときに使える旅行向けの頼み方です。"],
    ["Do I have a few minutes before boarding?", "搭乗まで少し時間はありますか", "出発前に余裕があるか確認したいときの表現です。"],
    ["Where can I find the taxi stand?", "タクシー乗り場はどこですか", "空港や駅で移動手段を探すときに使えます。"],
    ["Is this the right platform?", "このホームで合っていますか", "電車に乗る前に場所を確認したいときの表現です。"],
    ["Could you tell me when to get off?", "どこで降りればいいか教えてもらえますか", "バスや電車で降車場所が不安なときに役立ちます。"],
    ["Can I pay with this card?", "このカードで支払えますか", "手持ちのカードが使えるか確認する短い表現です。"],
    ["Do you have a smaller bag?", "小さめの袋はありますか", "買い物で包装や袋の大きさを調整したいときに使えます。"],
    ["Could you pack this separately?", "これは別に包んでもらえますか", "お土産や壊れやすい物を分けて入れてほしいときに便利です。"],
    ["Is this area safe at night?", "このあたりは夜でも安全ですか", "宿泊先や移動先の治安を確認したいときの表現です。"],
    ["Where can I get a local map?", "現地の地図はどこでもらえますか", "観光案内所やホテルで地図を探すときに使えます。"],
    ["Could you mark it on the map?", "地図に印をつけてもらえますか", "場所を視覚的に確認したいときの定番表現です。"],
    ["Is there an extra charge?", "追加料金はかかりますか", "サービスや変更に費用が発生するか確認できます。"],
    ["Can I change the date of my ticket?", "チケットの日付を変更できますか", "予約や乗車券の日程変更を相談する表現です。"],
    ["Where can I make a reservation?", "どこで予約できますか", "施設、ツアー、レストランなどの予約方法を聞くときに使えます。"],
    ["Could you call this number for me?", "この番号に電話してもらえますか", "電話が難しい場面で相手に手伝いを頼む実用表現です。"],
    ["I lost my way.", "道に迷いました", "迷ったことを短く伝える旅行必須フレーズです。"],
    ["I'm looking for this address.", "この住所を探しています", "住所を見せながら目的地を探していることを伝えられます。"],
    ["Can I leave and come back later?", "一度出てあとで戻れますか", "施設や店で再入場や一時退出が可能か確認する表現です。"],
    ["Do you have a seat by the aisle?", "通路側の席はありますか", "飛行機や劇場、レストランで座席の希望を伝える表現です。"],
    ["Could you take a quick photo of us?", "私たちの写真を一枚撮ってもらえますか", "旅行先で写真撮影をお願いする自然な一言です。"]
  ]
};

const basicPhraseWords = dedupeEntries([
  ...legacyPhrases.beginner.words,
  ...buildEntries(basicPhraseExpansion),
  ...buildEntries(practicalPhraseBoost.basic),
  ...buildEntries([
    ["See you tomorrow.", "また明日ね", "別れ際に次の日また会う予定があるときの自然な一言です。See you later よりも日時がはっきりしています。"],
    ["What time is it now?", "今何時ですか", "時刻をたずねる基本表現です。now を入れることで、今の時刻を知りたい意図がより明確になります。"],
    ["I'm hungry.", "お腹が空きました", "体調や状態を短く伝える基本表現です。食事の提案につなげやすい一言でもあります。"],
    ["I'm tired.", "疲れました", "学校や仕事、移動のあとに気分を素直に伝える表現です。I'm a little tired. とすると少しやわらかく聞こえます。"],
    ["Can you show me?", "見せてもらえますか", "やり方や場所、画面などを実際に見たいときに使える便利な表現です。説明だけで足りないときに役立ちます。"],
    ["Please wait a moment.", "少し待ってください", "相手に短く待ってもらいたいときの丁寧な表現です。a moment を入れると、少しの時間だと伝えられます。"],
    ["This is my friend.", "こちらは私の友だちです", "人を紹介するときの基本表現です。This is my brother. や This is my teacher. にもそのまま応用できます。"],
    ["I like this one.", "私はこれが好きです", "いくつかの選択肢の中から好みを伝えるときの言い方です。買い物や注文でも使いやすい表現です。"],
    ["Where are you from?", "どこの出身ですか", "初対面の会話でよく使う質問です。国、地域、町など相手の背景を自然にたずねられます。"],
    ["What do you do after school?", "放課後は何をしますか", "学生同士の会話で使いやすい質問です。after school を work に変えると仕事後の予定にも応用できます。"],
    ["I'm ready.", "準備できました", "出発や開始の前に自分の状態を短く伝える基本表現です。会話でも行動の区切りでも使いやすいです。"],
    ["Please come in.", "どうぞ入ってください", "家や部屋、教室などに人を迎え入れるときの自然な表現です。"],
    ["Can you hear me?", "聞こえますか", "対面でもオンラインでも使える基本表現です。音声が届いているか確認したいときに便利です。"],
    ["I forgot my umbrella.", "傘を忘れました", "忘れ物を伝える短い実用表現です。my umbrella の部分を入れ替えるだけで応用しやすいです。"],
    ["Let's go together.", "一緒に行きましょう", "友だちや家族を誘うときの基本表現です。会話を前向きに進めやすい一言です。"],
    ["I'm almost there.", "もうすぐ着きます", "待ち合わせの直前に今の状況を短く伝える便利な表現です。arrive soon より自然な会話になりやすいです。"],
    ["Can I ask you something?", "ちょっと聞いてもいいですか", "質問に入る前のやわらかい切り出しです。いきなり本題に入るより自然に会話を始められます。"],
    ["Just a second, please.", "少しだけ待ってください", "短く待ってもらいたいときの定番表現です。a moment より会話でテンポよく使われることも多いです。"],
    ["I'm not sure yet.", "まだよくわかりません", "判断や返答を保留したいときの自然な表現です。強く断定しないので会話がやわらかくなります。"],
    ["That sounds good.", "いいですね", "提案や誘いに前向きに反応するときの短く使いやすい一言です。会話のテンポを崩さず返せます。"],
    ["Can you take a picture for us?", "写真を撮ってもらえますか", "旅行や外出先で非常によく使う実用フレーズです。for us を変えれば対象も簡単に変えられます。"],
    ["I'm just checking.", "確認しているだけです", "すぐに決めるわけではなく、様子を見ていることを伝える表現です。店や案内画面を見る場面でも使いやすいです。"],
    ["Do you have a minute?", "少し時間ありますか", "相手に少し話す時間があるか確認する定番表現です。仕事でも日常でも使いやすいです。"]
  ])
]);

const practicalPhraseWords = dedupeEntries([
  ...legacyPhrases.intermediate.words,
  ...legacyPhrases.advanced.words,
  ...buildEntries(practicalPhraseExpansion),
  ...buildEntries(practicalPhraseBoost.practical),
  ...buildEntries([
    ["Could you write it down for me?", "書いてもらえますか", "聞き取りにくい単語や住所、番号などを文字で確認したいときの表現です。口頭だけでは不安な場面で役立ちます。"],
    ["I need a little more time.", "もう少し時間が必要です", "その場ですぐに決められないときや、準備に少し時間が欲しいときに使える表現です。丁寧で使い回しやすい一言です。"],
    ["That depends on the situation.", "それは状況によります", "一つの答えに決めきれないときに使う自然な表現です。depends on ... で「〜次第だ」という意味になります。"],
    ["I'm trying to remember the word.", "その単語を思い出そうとしています", "言いたいことはあるのに単語が出てこないときのつなぎとして便利です。会話を止めずに続けやすくなります。"],
    ["Can you give me an example?", "例を挙げてもらえますか", "説明をもっと具体的に理解したいときの定番表現です。抽象的な話を実例に落としたい場面で使えます。"],
    ["I didn't catch the last part.", "最後の部分を聞き取れませんでした", "全部ではなく一部だけ聞き逃したときに自然な言い方です。say that again よりも具体的に伝えられます。"],
    ["Let's keep it simple.", "簡単にいきましょう", "話を複雑にしすぎず、分かりやすく進めたいときの表現です。説明や相談の場面で使いやすいです。"],
    ["What's the easiest way to get there?", "そこへ行く一番簡単な方法は何ですか", "移動手段や行き方を比較しながら知りたいときに便利です。fastest ではなく easiest を使うので負担の少ない方法をたずねられます。"],
    ["I may need to change the plan.", "予定を変更する必要があるかもしれません", "確定ではないが、予定変更の可能性を先に伝える表現です。相手に心づもりをしてもらえます。"],
    ["Could you check if it's available?", "利用できるか確認してもらえますか", "空き状況や在庫、対応可否を確認してほしいときの定番表現です。available がとても実用的です。"],
    ["I'm still thinking about it.", "まだ考えています", "即答を避けたいときのやわらかい返しです。断定せずに保留の姿勢を自然に伝えられます。"],
    ["That would make things easier.", "そうすると楽になります", "提案や選択肢について、よりやりやすくなると伝える表現です。things を使って状況全体をまとめて表せます。"],
    ["Could you send me the details later?", "詳細をあとで送ってもらえますか", "その場で全部覚えられないときや、文章で確認したいときに便利な表現です。later によって急ぎではないことも伝わります。"],
    ["Let's focus on the main point first.", "まず要点から見ましょう", "話が広がりすぎたときに、中心となる論点へ戻すための表現です。"],
    ["Can we take a short break?", "少し休憩できますか", "会話や作業が続いているときに短い休憩を提案する自然な言い方です。オンラインでも対面でも使えます。"],
    ["I'll explain it another way.", "別の言い方で説明します", "今の説明では伝わりにくそうなときに言い換えを申し出る表現です。学習中の会話でも非常に実用的です。"],
    ["That's not exactly what I meant.", "私が言いたかったのは少し違います", "誤解をやわらかく修正するときに便利な表現です。相手を強く否定せず言い直せます。"],
    ["Let me check my schedule first.", "まず予定を確認させてください", "約束の返事や日程調整の前にひと呼吸置きたいときの定番表現です。"],
    ["Could you be a little more specific?", "もう少し具体的に言ってもらえますか", "説明が抽象的なときに、内容を深掘りしたい場面で使える実用表現です。"],
    ["I see your point, but I have a concern.", "おっしゃることはわかりますが、気になる点があります", "相手を立てつつ自分の懸念も伝えたいときに便利な言い回しです。"],
    ["Let's decide that later.", "それはあとで決めましょう", "今すぐ決める必要のないことをいったん保留にする表現です。会話の整理にも役立ちます。"],
    ["Could you send me the link?", "リンクを送ってもらえますか", "サイト、地図、資料などを共有してほしいときの短く実用的な表現です。"],
    ["I'm trying to say this in English.", "英語で言おうとしているところです", "言葉を探しながら会話をつなぐときの自然な一言です。学習者向けにかなり実用的です。"]
  ])
]);

const businessPhraseWords = dedupeEntries([
  ...legacyPhrases.business.words,
  ...buildEntries(businessPhraseExpansion),
  ...buildEntries(practicalPhraseBoost.business),
  ...buildEntries([
    ["Could you share the file with the team?", "そのファイルをチームに共有してもらえますか", "社内の共有作業でよく使う表現です。share A with B で「AをBに共有する」という形になります。"],
    ["Let's confirm the deadline once again.", "締切をもう一度確認しましょう", "日程トラブルを防ぐために、あらためて確認するときの言い方です。once again を入れると再確認の意図が明確です。"],
    ["We need to prioritize the urgent tasks.", "急ぎの作業を優先する必要があります", "タスクが多いときに優先順位をはっきりさせる表現です。prioritize はビジネスで非常によく使います。"],
    ["I'll prepare a short summary.", "短い要約を用意します", "会議後ややり取りのあとで要点を整理して共有するときに自然な一言です。short summary で簡潔さも伝えられます。"],
    ["Could you update the spreadsheet?", "表を更新していただけますか", "数値管理や進捗表の更新を頼む場面で使いやすい表現です。spreadsheet は実務で頻出です。"],
    ["Let's move this discussion offline.", "この件は別で話しましょう", "全体会議の場ではなく、後で個別に詳しく話したいときの表現です。offline は「オフラインで」というより「この場の外で」の意味で使われます。"],
    ["We should clarify the requirements.", "要件を明確にしたほうがよいです", "作業の前提や条件があいまいなときに使う実務表現です。requirements は開発でも事務でも頻出です。"],
    ["I'll send the revised draft this afternoon.", "修正版の下書きを今日の午後に送ります", "修正後の資料送付予定を伝える自然な文です。revised draft はそのまま実務で使えます。"],
    ["Please keep the client informed.", "顧客に状況共有をお願いします", "担当者へ継続的な報告を依頼するときの表現です。keep A informed で「Aに状況を知らせ続ける」となります。"],
    ["Let's review the risks before launch.", "公開前にリスクを確認しましょう", "リリース前の確認で使いやすい表現です。before launch によってタイミングが明確になります。"],
    ["Could you add this to the agenda?", "これを議題に追加してもらえますか", "会議前に話したい項目を入れてほしいときの表現です。agenda は会議運営で頻出です。"],
    ["I'll follow up with the vendor.", "取引先に確認を取ります", "外部先とのやり取りを自分が担当すると伝える表現です。follow up with ... が実務で使いやすい形です。"],
    ["We need a quick status update.", "短い進捗共有が必要です", "長い説明ではなく、要点だけの進捗確認を求める表現です。status update は会議やチャットで非常によく使われます。"],
    ["Could you confirm the final version?", "最終版を確認してもらえますか", "修正版が複数あるときに、最終版で問題ないか見てもらう定番表現です。"],
    ["Let's set a realistic timeline.", "現実的なスケジュールを立てましょう", "無理のない進行計画を作りたいときの表現です。realistic が実務の温度感によく合います。"],
    ["Could you send me a quick summary after the meeting?", "会議後に簡単な要約を送ってもらえますか", "その場で全部メモできないときに便利な依頼表現です。after the meeting を変えれば応用もしやすいです。"],
    ["We need to make sure everyone is aligned.", "全員の認識をそろえる必要があります", "会議やプロジェクト進行で認識合わせをしたいときの頻出表現です。aligned がビジネス会話でよく使われます。"],
    ["I'll double-check the numbers.", "数字を再確認します", "数値ミスを防ぐために確認し直すときの自然な一言です。double-check が非常に実用的です。"],
    ["Could we push this back to next week?", "これは来週にずらせますか", "予定や締切を少し後ろへ動かしたいときの実務表現です。push back は日程変更でよく使います。"],
    ["Let's keep the discussion brief.", "議論は手短に進めましょう", "時間が限られている会議で役立つ表現です。brief によって短く要点中心で進める意図が出ます。"],
    ["I'll share the notes by the end of the day.", "本日中にメモを共有します", "会議後の共有予定を明確に伝える実用表現です。by the end of the day が仕事でよく使われます。"],
    ["Can we revisit this after lunch?", "これは昼食後にもう一度見直せますか", "その場で結論を出さず、少し後で再検討したいときに便利な表現です。"],
    ["We may need more time to review it.", "確認にはもう少し時間が必要かもしれません", "即答できないときに自然に時間をもらえる表現です。review it が実務で使いやすい形です。"],
    ["Please flag anything unusual.", "気になる点があれば知らせてください", "チェック依頼のときに、異常や違和感を見つけたら共有してほしいと伝える表現です。"]
  ])
]);

const travelPhraseWords = dedupeEntries([
  ...legacyPhrases.travel.words,
  ...buildEntries(travelPhraseExpansion),
  ...buildEntries(practicalPhraseBoost.travel),
  ...buildEntries([
    ["Is this seat taken?", "この席は空いていますか", "電車、バス、待合室などで座ってよいか確認する基本表現です。taken は「使われている、埋まっている」という意味です。"],
    ["Could I have a non-smoking room?", "禁煙の部屋をお願いできますか", "ホテルで部屋の希望を伝える定番表現です。smoking room と対で覚えると便利です。"],
    ["Can I leave my bag after check-out?", "チェックアウト後も荷物を預けられますか", "ホテルを出たあとに身軽に行動したいときによく使う表現です。after check-out が実用的です。"],
    ["How long is the wait?", "どのくらい待ちますか", "列、レストラン、窓口などで待ち時間をたずねる短く便利な表現です。"],
    ["Which bus goes to the city center?", "どのバスが市内中心部へ行きますか", "バス移動で路線を確認したいときに使う表現です。goes to ... で目的地へ向かう交通手段を聞けます。"],
    ["Could you tell me the Wi-Fi password?", "Wi-Fiのパスワードを教えてもらえますか", "ホテルやカフェで非常によく使う表現です。password をはっきり入れると伝わりやすいです。"],
    ["I'd like a table near the window.", "窓際の席をお願いします", "レストランで席の希望を丁寧に伝える言い方です。near the window は景色が見たいときに便利です。"],
    ["Can I have this to go?", "これを持ち帰りにできますか", "食べ物や飲み物を持ち帰りたいときの定番表現です。アメリカ英語圏で特によく使われます。"],
    ["Do you have anything without dairy?", "乳製品を使っていないものはありますか", "食事制限やアレルギー対応で便利な表現です。without dairy で乳製品なしを自然に伝えられます。"],
    ["Where can I buy a SIM card?", "SIMカードはどこで買えますか", "海外到着後に通信手段を確保したいときの実用表現です。空港や街中でそのまま使えます。"],
    ["Is it safe to walk here at night?", "このあたりは夜に歩いても安全ですか", "治安を確認したいときの丁寧で実用的な質問です。at night を入れると夜間の安全性に限定できます。"],
    ["Could you help me find my hotel?", "ホテルを探すのを手伝ってもらえますか", "道に迷ったときや現在地が分からないときに使える表現です。find my hotel で目的が明確に伝わります。"],
    ["How much is the entrance fee?", "入場料はいくらですか", "観光施設や展示会で料金を確認する基本表現です。admission fee と言い換えられる場面もあります。"],
    ["Can I take pictures here?", "ここで写真を撮ってもいいですか", "撮影可否を確認したいときの定番表現です。寺社や美術館では特に役立ちます。"],
    ["Where is the nearest convenience store?", "一番近いコンビニはどこですか", "旅行中によく必要になる店を探す実用表現です。nearest によって近場を探していることが明確になります。"],
    ["Could I have another towel?", "タオルをもう一枚もらえますか", "ホテルで追加備品をお願いするときに自然な表現です。another を使うと追加依頼だと伝わります。"],
    ["What time should I check out?", "チェックアウトは何時までですか", "ホテルの退出時刻を確認したいときの表現です。ルールをはっきり確認できて便利です。"],
    ["Can you recommend a local dish?", "地元のおすすめ料理はありますか", "観光先で名物料理を知りたいときの自然な質問です。local dish がその土地らしさを表します。"],
    ["Is breakfast included?", "朝食は含まれていますか", "宿泊予約の内容を確認するときに非常によく使う表現です。included によって料金に入っているかをたずねられます。"],
    ["Which line should I take?", "どの路線に乗ればいいですか", "電車や地下鉄で路線選びに迷ったときの基本表現です。travel でかなり実用的です。"],
    ["Can I store my luggage here?", "ここで荷物を預けられますか", "駅やホテルで荷物預かりの有無を確認したいときに便利な表現です。store my luggage が実用的です。"],
    ["Is there a charger I can use?", "使える充電器はありますか", "スマホの充電が必要なときに短く状況を伝えられる表現です。旅行中の頻出場面に合います。"],
    ["Could you tell me the gate number?", "搭乗口の番号を教えてもらえますか", "空港で搭乗ゲートを確認したいときに使う実用表現です。"],
    ["Do I need to print this ticket?", "このチケットは印刷が必要ですか", "電子チケットがそのまま使えるか確認したいときに便利な質問です。"],
    ["Is there a place to charge my phone?", "スマホを充電できる場所はありますか", "空港、駅、カフェなどで非常に実用的な表現です。"],
    ["Can I have a late check-out?", "チェックアウトを遅らせられますか", "ホテルで退出時間を延ばせるか相談するときの定番表現です。"],
    ["Where should I line up?", "どこに並べばいいですか", "乗車列や入場列が分かりにくいときに短く聞ける便利な表現です。"],
    ["Can I get a refill on this?", "これのおかわりはできますか", "飲み物の追加や補充が可能かを確認したいときに使えます。"],
    ["Could you write down the address for me?", "住所を書いてもらえますか", "タクシーや道案内で見せられる形にしたいときに役立つ旅行フレーズです。"]
  ])
]);

export const phrases = {
  basic: {
    label: "初級",
    description: "中学生レベルの一般会話でまず使いたい短くて基本的なフレーズです。",
    words: basicPhraseWords
  },
  practical: {
    label: "実用単語",
    description: "予定調整、説明、聞き返し、相談など日常を広げる実用フレーズです。",
    words: practicalPhraseWords
  },
  business: {
    label: "ビジネス",
    description: "会議、共有、確認、依頼、進行管理で使いやすい仕事向けのフレーズです。",
    words: businessPhraseWords
  },
  travel: {
    label: "旅行",
    description: "移動、宿泊、注文、買い物、トラブル対応でそのまま使える旅行フレーズです。",
    words: travelPhraseWords
  }
};
