function buildEntries(items) {
  return items.map(([english, japanese]) => ({ english, japanese }));
}

function dedupeEntries(items) {
  const seen = new Set();

  return items.filter(({ english }) => {
    const key = english.trim().toLowerCase();

    if (seen.has(key)) {
      return false;
    }

    seen.add(key);
    return true;
  });
}

const beginnerWords = dedupeEntries(
  []
  .concat(buildEntries([
    ["I", "私"],
    ["you", "あなた"],
    ["he", "彼"],
    ["she", "彼女"],
    ["it", "それ"],
    ["we", "私たち"],
    ["they", "彼ら"],
    ["this", "これ"],
    ["that", "あれ"],
    ["these", "これら"],
    ["those", "あれら"],
    ["here", "ここ"],
    ["there", "そこ"],
    ["who", "だれ"],
    ["what", "何"],
    ["when", "いつ"],
    ["where", "どこ"],
    ["why", "なぜ"],
    ["how", "どうやって"],
    ["yes", "はい"],
    ["no", "いいえ"],
    ["not", "〜ない"],
    ["all", "すべて"],
    ["some", "いくつかの"],
    ["any", "いくつかの / どんな〜でも"],
    ["many", "たくさんの"],
    ["much", "多くの"],
    ["few", "少しの"],
    ["more", "より多くの"],
    ["most", "ほとんどの"],
    ["other", "ほかの"],
    ["another", "もう一つの"],
    ["same", "同じ"],
    ["different", "違う"],
    ["one", "1"],
    ["two", "2"],
    ["three", "3"],
    ["four", "4"],
    ["five", "5"],
    ["six", "6"],
    ["seven", "7"],
    ["eight", "8"],
    ["nine", "9"],
    ["ten", "10"],
    ["eleven", "11"],
    ["twelve", "12"],
    ["thirteen", "13"],
    ["fourteen", "14"],
    ["fifteen", "15"],
    ["sixteen", "16"],
    ["seventeen", "17"],
    ["eighteen", "18"],
    ["nineteen", "19"],
    ["twenty", "20"],
    ["first", "最初の"],
    ["second", "2番目の"],
    ["third", "3番目の"],
    ["and", "そして"],
    ["but", "しかし"],
    ["or", "または"],
    ["because", "なぜなら"],
    ["if", "もし"],
    ["then", "そのとき"],
    ["so", "だから"],
    ["with", "〜と一緒に"],
    ["without", "〜なしで"],
    ["for", "〜のために"],
    ["from", "〜から"],
    ["to", "〜へ"],
    ["at", "〜で"],
    ["in", "〜の中で"],
    ["on", "〜の上に"],
    ["under", "〜の下に"],
    ["near", "〜の近くに"],
    ["between", "〜の間に"],
    ["about", "〜について"],
    ["before", "〜の前に"],
    ["after", "〜の後に"]
  ]))
  .concat(buildEntries([
    ["person", "人"],
    ["people", "人々"],
    ["name", "名前"],
    ["friend", "友だち"],
    ["family", "家族"],
    ["mother", "母"],
    ["father", "父"],
    ["mom", "お母さん"],
    ["dad", "お父さん"],
    ["parent", "親"],
    ["child", "子ども"],
    ["baby", "赤ちゃん"],
    ["boy", "男の子"],
    ["girl", "女の子"],
    ["man", "男性"],
    ["woman", "女性"],
    ["brother", "兄弟"],
    ["sister", "姉妹"],
    ["son", "息子"],
    ["daughter", "娘"],
    ["husband", "夫"],
    ["wife", "妻"],
    ["grandfather", "祖父"],
    ["grandmother", "祖母"],
    ["uncle", "おじ"],
    ["aunt", "おば"],
    ["cousin", "いとこ"],
    ["neighbor", "近所の人"],
    ["classmate", "クラスメート"],
    ["teacher", "先生"],
    ["student", "生徒"],
    ["doctor", "医者"],
    ["nurse", "看護師"],
    ["driver", "運転手"],
    ["cook", "料理人"],
    ["chef", "シェフ"],
    ["worker", "働く人"],
    ["staff", "スタッフ"],
    ["manager", "管理者"],
    ["boss", "上司"],
    ["coworker", "同僚"],
    ["customer", "お客"],
    ["guest", "客"],
    ["tourist", "観光客"],
    ["guide", "案内人"],
    ["police officer", "警察官"],
    ["firefighter", "消防士"],
    ["engineer", "技術者"],
    ["designer", "デザイナー"],
    ["artist", "芸術家"],
    ["musician", "音楽家"],
    ["player", "選手"],
    ["owner", "所有者"],
    ["leader", "リーダー"],
    ["member", "メンバー"],
    ["team", "チーム"],
    ["group", "グループ"],
    ["couple", "カップル"],
    ["age", "年齢"],
    ["job", "仕事"],
    ["career", "職業人生"]
  ]))
  .concat(buildEntries([
    ["home", "家"],
    ["house", "住宅"],
    ["apartment", "アパート"],
    ["building", "建物"],
    ["room", "部屋"],
    ["living room", "居間"],
    ["bedroom", "寝室"],
    ["bathroom", "浴室"],
    ["restroom", "トイレ"],
    ["kitchen", "台所"],
    ["hallway", "廊下"],
    ["stairs", "階段"],
    ["elevator", "エレベーター"],
    ["door", "ドア"],
    ["window", "窓"],
    ["wall", "壁"],
    ["floor", "床"],
    ["ceiling", "天井"],
    ["roof", "屋根"],
    ["key", "鍵"],
    ["lock", "鍵穴"],
    ["table", "テーブル / 表"],
    ["desk", "机"],
    ["chair", "椅子"],
    ["sofa", "ソファ"],
    ["bed", "ベッド"],
    ["pillow", "枕"],
    ["blanket", "毛布"],
    ["sheet", "シーツ"],
    ["towel", "タオル"],
    ["mirror", "鏡"],
    ["lamp", "ランプ"],
    ["light", "明かり / 軽い"],
    ["fan", "扇風機"],
    ["air conditioner", "エアコン"],
    ["heater", "暖房器具"],
    ["refrigerator", "冷蔵庫"],
    ["freezer", "冷凍庫"],
    ["microwave", "電子レンジ"],
    ["oven", "オーブン"],
    ["stove", "コンロ"],
    ["sink", "流し台"],
    ["cup", "カップ"],
    ["glass", "グラス"],
    ["plate", "皿"],
    ["bowl", "ボウル"],
    ["fork", "フォーク"],
    ["knife", "ナイフ"],
    ["spoon", "スプーン"],
    ["chopsticks", "箸"],
    ["pan", "フライパン"],
    ["pot", "鍋"],
    ["bag", "かばん"],
    ["backpack", "リュック"],
    ["wallet", "財布"],
    ["purse", "小銭入れ"],
    ["umbrella", "傘"],
    ["watch", "腕時計 / 見る"],
    ["clock", "時計"],
    ["minute", "1分 / 少しの時間"],
    ["calendar", "カレンダー"],
    ["battery", "電池"]
  ]))
  .concat(buildEntries([
    ["water", "水"],
    ["tea", "お茶"],
    ["coffee", "コーヒー"],
    ["milk", "牛乳"],
    ["juice", "ジュース"],
    ["soda", "炭酸飲料"],
    ["wine", "ワイン"],
    ["beer", "ビール"],
    ["bread", "パン"],
    ["rice", "ご飯"],
    ["noodles", "麺"],
    ["soup", "スープ"],
    ["salad", "サラダ"],
    ["sandwich", "サンドイッチ"],
    ["hamburger", "ハンバーガー"],
    ["pizza", "ピザ"],
    ["pasta", "パスタ"],
    ["cake", "ケーキ"],
    ["cookie", "クッキー"],
    ["ice cream", "アイスクリーム"],
    ["breakfast", "朝食"],
    ["lunch", "昼食"],
    ["dinner", "夕食"],
    ["snack", "軽食"],
    ["meal", "食事"],
    ["menu", "メニュー"],
    ["dish", "料理"],
    ["order", "注文 / 順序"],
    ["bill", "会計"],
    ["receipt", "レシート"],
    ["apple", "りんご"],
    ["banana", "バナナ"],
    ["orange", "オレンジ"],
    ["grape", "ぶどう"],
    ["strawberry", "いちご"],
    ["peach", "桃"],
    ["lemon", "レモン"],
    ["melon", "メロン"],
    ["pineapple", "パイナップル"],
    ["tomato", "トマト"],
    ["potato", "じゃがいも"],
    ["onion", "玉ねぎ"],
    ["carrot", "にんじん"],
    ["cabbage", "キャベツ"],
    ["lettuce", "レタス"],
    ["corn", "とうもろこし"],
    ["bean", "豆"],
    ["egg", "卵"],
    ["meat", "肉"],
    ["beef", "牛肉"],
    ["pork", "豚肉"],
    ["chicken", "鶏肉"],
    ["fish", "魚"],
    ["shrimp", "えび"],
    ["cheese", "チーズ"],
    ["butter", "バター"],
    ["salt", "塩"],
    ["sugar", "砂糖"],
    ["pepper", "こしょう"],
    ["sauce", "ソース"]
  ]))
  .concat(buildEntries([
    ["place", "場所"],
    ["area", "地域"],
    ["street", "通り"],
    ["road", "道路"],
    ["corner", "角"],
    ["crosswalk", "横断歩道"],
    ["bridge", "橋"],
    ["park", "公園"],
    ["station", "駅"],
    ["bus stop", "バス停"],
    ["airport", "空港"],
    ["terminal", "ターミナル"],
    ["gate", "搭乗口"],
    ["hotel", "ホテル"],
    ["hostel", "ホステル"],
    ["restaurant", "レストラン"],
    ["cafe", "カフェ"],
    ["shop", "店"],
    ["store", "店舗"],
    ["supermarket", "スーパー"],
    ["convenience store", "コンビニ"],
    ["market", "市場"],
    ["pharmacy", "薬局"],
    ["hospital", "病院"],
    ["clinic", "診療所"],
    ["bank", "銀行"],
    ["ATM", "ATM"],
    ["post office", "郵便局"],
    ["library", "図書館"],
    ["museum", "博物館"],
    ["school", "学校"],
    ["office", "会社"],
    ["station platform", "駅のホーム"],
    ["platform", "ホーム"],
    ["ticket machine", "券売機"],
    ["map", "地図"],
    ["guidebook", "ガイドブック"],
    ["address", "住所 / 宛先 / 対応する"],
    ["city", "都市"],
    ["town", "町"],
    ["village", "村"],
    ["country", "国"],
    ["beach", "海辺"],
    ["sea", "海"],
    ["river", "川"],
    ["lake", "湖"],
    ["mountain", "山"],
    ["forest", "森"],
    ["island", "島"],
    ["bus", "バス"],
    ["train", "電車"],
    ["subway", "地下鉄"],
    ["taxi", "タクシー"],
    ["car", "車"],
    ["bicycle", "自転車"],
    ["motorcycle", "バイク"],
    ["airplane", "飛行機"],
    ["ship", "船"],
    ["ticket", "切符"],
    ["fare", "運賃"],
    ["seat", "座席"]
  ]))
  .concat(buildEntries([
    ["head", "頭"],
    ["face", "顔"],
    ["hair", "髪"],
    ["eye", "目"],
    ["ear", "耳"],
    ["nose", "鼻"],
    ["mouth", "口"],
    ["tooth", "歯"],
    ["neck", "首"],
    ["shoulder", "肩"],
    ["arm", "腕"],
    ["hand", "手"],
    ["finger", "指"],
    ["back", "背中"],
    ["stomach", "お腹"],
    ["leg", "脚"],
    ["knee", "ひざ"],
    ["foot", "足"],
    ["toe", "足の指"],
    ["heart", "心臓"],
    ["body", "体"],
    ["health", "健康"],
    ["medicine", "薬"],
    ["doctor", "医者"],
    ["dentist", "歯医者"],
    ["nurse", "看護師"],
    ["fever", "熱"],
    ["cold", "風邪"],
    ["cough", "せき"],
    ["headache", "頭痛"],
    ["stomachache", "腹痛"],
    ["pain", "痛み"],
    ["injury", "けが"],
    ["bandage", "包帯"],
    ["mask", "マスク"],
    ["soap", "石けん"],
    ["shampoo", "シャンプー"],
    ["toothbrush", "歯ブラシ"],
    ["toothpaste", "歯みがき粉"],
    ["healthy", "健康的な"],
    ["sick", "具合が悪い"],
    ["tired", "疲れた"],
    ["hungry", "お腹がすいた"],
    ["thirsty", "喉が渇いた"],
    ["sleepy", "眠い"],
    ["happy", "うれしい"],
    ["sad", "悲しい"],
    ["angry", "怒った"],
    ["worried", "心配した"],
    ["scared", "こわい"],
    ["excited", "わくわくした"],
    ["busy", "忙しい"],
    ["free", "暇な"],
    ["safe", "安全な"],
    ["dangerous", "危険な"],
    ["careful", "注意深い"],
    ["relaxed", "落ち着いた"],
    ["strong", "強い"],
    ["weak", "弱い"],
    ["better", "より良い"]
  ]))
  .concat(buildEntries([
    ["shirt", "シャツ"],
    ["T-shirt", "Tシャツ"],
    ["jacket", "ジャケット"],
    ["coat", "コート"],
    ["sweater", "セーター"],
    ["hoodie", "パーカー"],
    ["dress", "ドレス"],
    ["skirt", "スカート"],
    ["pants", "ズボン"],
    ["jeans", "ジーンズ"],
    ["shorts", "短パン"],
    ["socks", "靴下"],
    ["shoes", "靴"],
    ["boots", "ブーツ"],
    ["hat", "帽子"],
    ["cap", "キャップ"],
    ["glasses", "めがね"],
    ["sunglasses", "サングラス"],
    ["ring", "指輪"],
    ["necklace", "ネックレス"],
    ["bag", "バッグ"],
    ["size", "サイズ"],
    ["small", "小さい"],
    ["medium", "中くらいの"],
    ["large", "大きい"],
    ["price", "値段"],
    ["sale", "セール"],
    ["discount", "割引"],
    ["cash", "現金"],
    ["credit card", "クレジットカード"],
    ["debit card", "デビットカード"],
    ["change", "おつり / 変化 / 変える"],
    ["customer service", "案内係"],
    ["fitting room", "試着室"],
    ["shopping bag", "買い物袋"],
    ["gift", "贈り物"],
    ["souvenir", "お土産"],
    ["package", "包み"],
    ["box", "箱"],
    ["bottle", "びん"],
    ["can", "缶"],
    ["plastic bag", "ビニール袋"],
    ["favorite color", "好きな色"],
    ["red", "赤"],
    ["blue", "青"],
    ["green", "緑"],
    ["yellow", "黄色"],
    ["black", "黒"],
    ["white", "白"],
    ["gray", "灰色"],
    ["brown", "茶色"],
    ["pink", "ピンク"],
    ["purple", "紫"],
    ["orange color", "オレンジ色"],
    ["clean", "きれいな"],
    ["dirty", "汚れた"],
    ["new", "新しい"],
    ["old", "古い"],
    ["pretty", "かわいい"],
    ["simple", "シンプルな"]
  ]))
  .concat(buildEntries([
    ["book", "本 / 予約する"],
    ["notebook", "ノート"],
    ["pen", "ペン"],
    ["pencil", "鉛筆"],
    ["eraser", "消しゴム"],
    ["marker", "マーカー"],
    ["paper", "紙"],
    ["dictionary", "辞書"],
    ["question", "質問"],
    ["answer", "答え"],
    ["lesson", "授業"],
    ["class", "授業"],
    ["homework", "宿題"],
    ["test", "テスト"],
    ["exam", "試験"],
    ["score", "点数"],
    ["grade", "成績"],
    ["practice", "練習"],
    ["example", "例"],
    ["note", "メモ"],
    ["meeting", "会議"],
    ["report", "報告"],
    ["email", "メール"],
    ["message", "メッセージ"],
    ["call", "電話"],
    ["computer", "コンピューター"],
    ["laptop", "ノートパソコン"],
    ["tablet", "タブレット"],
    ["phone", "スマホ"],
    ["screen", "画面"],
    ["keyboard", "キーボード"],
    ["mouse", "マウス"],
    ["printer", "プリンター"],
    ["charger", "充電器"],
    ["cable", "ケーブル"],
    ["battery", "バッテリー"],
    ["Internet", "インターネット"],
    ["website", "ウェブサイト"],
    ["page", "ページ"],
    ["file", "ファイル / 書類"],
    ["folder", "フォルダー"],
    ["password", "パスワード"],
    ["account", "アカウント"],
    ["user name", "ユーザー名"],
    ["button", "ボタン"],
    ["link", "リンク"],
    ["video", "動画"],
    ["photo", "写真"],
    ["music", "音楽"],
    ["game", "ゲーム"],
    ["news", "ニュース"],
    ["work", "仕事 / 働く"],
    ["company", "会社"],
    ["office", "職場"],
    ["schedule", "予定"],
    ["task", "作業"],
    ["plan", "計画"],
    ["idea", "考え"],
    ["problem", "問題"],
    ["solution", "解決"]
  ]))
  .concat(buildEntries([
    ["be", "〜である"],
    ["have", "持っている"],
    ["do", "する"],
    ["make", "作る"],
    ["get", "得る"],
    ["take", "取る"],
    ["put", "置く"],
    ["use", "使う"],
    ["need", "必要とする"],
    ["want", "欲しい"],
    ["like", "好き"],
    ["love", "とても好き"],
    ["know", "知っている"],
    ["think", "思う"],
    ["see", "見る"],
    ["watch", "見る"],
    ["look", "見る"],
    ["hear", "聞こえる"],
    ["listen", "聞く"],
    ["say", "言う"],
    ["speak", "話す"],
    ["talk", "話す"],
    ["ask", "たずねる"],
    ["answer", "答える"],
    ["call", "電話する"],
    ["help", "手伝う / 助ける"],
    ["find", "見つける"],
    ["give", "与える"],
    ["show", "見せる"],
    ["bring", "持ってくる"],
    ["send", "送る"],
    ["open", "開ける"],
    ["close", "閉める"],
    ["start", "始める"],
    ["finish", "終える"],
    ["try", "試す"],
    ["wait", "待つ"],
    ["keep", "保つ"],
    ["move", "動く"],
    ["walk", "歩く"],
    ["run", "走る"],
    ["sit", "座る"],
    ["stand", "立つ"],
    ["turn", "曲がる"],
    ["cross", "渡る"],
    ["ride", "乗る"],
    ["drive", "運転する"],
    ["travel", "旅行する"],
    ["visit", "訪れる"],
    ["stay", "滞在する"],
    ["return", "戻る"],
    ["buy", "買う"],
    ["pay", "支払う"],
    ["sell", "売る"],
    ["eat", "食べる"],
    ["drink", "飲む"],
    ["cook", "料理する"],
    ["wash", "洗う"],
    ["clean", "掃除する"],
    ["cut", "切る"],
    ["order", "注文する"],
    ["choose", "選ぶ"],
    ["wear", "着る"],
    ["change", "変える"],
    ["carry", "運ぶ"],
    ["hold", "持つ"],
    ["write", "書く"],
    ["read", "読む"],
    ["study", "勉強する"],
    ["learn", "学ぶ"],
    ["teach", "教える"],
    ["remember", "覚えている"],
    ["forget", "忘れる"],
    ["meet", "会う"],
    ["follow", "ついていく"],
    ["check", "確認する"],
    ["reserve", "予約する"],
    ["book", "予約する"],
    ["cancel", "キャンセルする"],
    ["arrive", "到着する"],
    ["leave", "出発する"],
    ["rest", "休む"],
    ["sleep", "眠る"],
    ["wake", "目覚める"],
    ["smile", "ほほえむ"],
    ["laugh", "笑う"],
    ["cry", "泣く"],
    ["enjoy", "楽しむ"],
    ["hope", "願う"],
    ["plan", "計画する"],
    ["prepare", "準備する"],
    ["share", "共有する"],
    ["borrow", "借りる"],
    ["lend", "貸す"]
  ]))
  .concat(buildEntries([
    ["today", "今日"],
    ["tomorrow", "明日"],
    ["yesterday", "昨日"],
    ["morning", "朝"],
    ["afternoon", "午後"],
    ["evening", "夕方"],
    ["night", "夜"],
    ["midnight", "真夜中"],
    ["day", "日"],
    ["week", "週"],
    ["month", "月"],
    ["year", "年"],
    ["weekend", "週末"],
    ["holiday", "休日"],
    ["vacation", "休暇"],
    ["spring", "春"],
    ["summer", "夏"],
    ["fall", "秋"],
    ["winter", "冬"],
    ["Monday", "月曜日"],
    ["Tuesday", "火曜日"],
    ["Wednesday", "水曜日"],
    ["Thursday", "木曜日"],
    ["Friday", "金曜日"],
    ["Saturday", "土曜日"],
    ["Sunday", "日曜日"],
    ["January", "1月"],
    ["February", "2月"],
    ["March", "3月"],
    ["April", "4月"],
    ["May", "5月"],
    ["June", "6月"],
    ["July", "7月"],
    ["August", "8月"],
    ["September", "9月"],
    ["October", "10月"],
    ["November", "11月"],
    ["December", "12月"],
    ["early", "早い"],
    ["late", "遅い"],
    ["now", "今"],
    ["soon", "すぐに"],
    ["later", "あとで"],
    ["always", "いつも"],
    ["usually", "たいてい"],
    ["sometimes", "ときどき"],
    ["often", "しばしば"],
    ["never", "決して〜ない"],
    ["again", "もう一度"],
    ["already", "すでに"],
    ["still", "まだ"],
    ["really", "本当に"],
    ["very", "とても"],
    ["quite", "かなり"],
    ["just", "ちょうど"],
    ["together", "一緒に"],
    ["inside", "内側に"],
    ["outside", "外側に"],
    ["left", "左 / 残された"],
    ["right side", "右側"],
    ["straight", "まっすぐ"],
    ["up", "上へ"],
    ["down", "下へ"],
    ["big", "大きい"],
    ["small", "小さい"],
    ["long", "長い"],
    ["short", "短い"],
    ["high", "高い"],
    ["low", "低い"],
    ["hot", "暑い / 熱い"],
    ["warm", "暖かい"],
    ["cool", "涼しい"],
    ["cold weather", "寒い"],
    ["rain", "雨"],
    ["snow", "雪"],
    ["wind", "風"],
    ["cloud", "雲"],
    ["sun", "太陽"],
    ["sunny", "晴れた"],
    ["rainy", "雨の"],
    ["cloudy", "くもった"],
    ["windy", "風の強い"],
    ["storm", "嵐"],
    ["clear", "晴れた"],
    ["bright", "明るい"],
    ["dark", "暗い"],
    ["easy", "簡単な"],
    ["hard", "難しい"],
    ["kind", "親切な / 種類"],
    ["nice", "感じのよい"],
    ["friendly", "親しみやすい"],
    ["important", "重要な"],
    ["possible", "可能な"],
    ["ready", "準備ができた"],
    ["full", "いっぱいの"],
    ["empty", "空の"]
  ]))
  .concat(buildEntries([
    ["price", "値段"],
    ["cost", "費用"],
    ["payment", "支払い"],
    ["pay", "支払う"],
    ["cash", "現金"],
    ["change", "おつり"],
    ["receipt", "レシート"],
    ["cashier", "レジ係"],
    ["register", "レジ"],
    ["wallet", "財布"],
    ["purse", "小さい財布"],
    ["coin", "硬貨"],
    ["bill", "紙幣"],
    ["credit card", "クレジットカード"],
    ["debit card", "デビットカード"],
    ["sale", "セール"],
    ["discount", "割引"],
    ["coupon", "クーポン"],
    ["tax", "税金"],
    ["customer", "客"],
    ["clerk", "店員"],
    ["store", "店"],
    ["market", "市場 / マーケット"],
    ["mall", "ショッピングモール"],
    ["shelf", "棚"],
    ["basket", "買い物かご"],
    ["cart", "カート"],
    ["fitting room", "試着室"],
    ["size", "サイズ"],
    ["medium", "中くらいの"],
    ["large", "大きいサイズの"],
    ["extra large", "特大サイズの"],
    ["try on", "試着する"],
    ["return", "返品する"],
    ["exchange", "交換する"],
    ["refund", "返金"],
    ["package", "荷物"],
    ["delivery", "配達"],
    ["address", "住所"],
    ["zip code", "郵便番号"],
    ["stamp", "切手"],
    ["mailbox", "郵便受け"],
    ["post office", "郵便局"],
    ["breakfast", "朝食"],
    ["lunch", "昼食"],
    ["dinner", "夕食"],
    ["snack", "軽食 / おやつ"],
    ["dessert", "デザート"],
    ["soup", "スープ"],
    ["salad", "サラダ"],
    ["rice", "ご飯"],
    ["bread", "パン"],
    ["noodle", "麺"],
    ["fruit", "果物"],
    ["vegetable", "野菜"],
    ["meat", "肉"],
    ["fish", "魚"],
    ["chicken", "鶏肉"],
    ["beef", "牛肉"],
    ["pork", "豚肉"],
    ["egg", "卵"],
    ["milk", "牛乳"],
    ["juice", "ジュース"],
    ["tea", "お茶"],
    ["coffee", "コーヒー"],
    ["sugar", "砂糖"],
    ["salt", "塩"],
    ["bottle", "ボトル"],
    ["cup", "カップ"],
    ["glass", "グラス"],
    ["plate", "皿"],
    ["bowl", "ボウル"],
    ["spoon", "スプーン"],
    ["fork", "フォーク"],
    ["knife", "ナイフ"],
    ["chopsticks", "箸"],
    ["napkin", "ナプキン"],
    ["straw", "ストロー"],
    ["check", "会計"],
    ["key", "鍵"],
    ["lock", "鍵をかける / 錠"],
    ["lamp", "ランプ"],
    ["pillow", "枕"],
    ["blanket", "毛布"],
    ["sheet", "シーツ"],
    ["towel", "タオル"],
    ["soap", "石けん"],
    ["shampoo", "シャンプー"],
    ["toothbrush", "歯ブラシ"],
    ["toothpaste", "歯みがき粉"],
    ["brush", "ブラシ"],
    ["comb", "くし"],
    ["dryer", "ドライヤー"],
    ["mirror", "鏡"],
    ["wall", "壁"],
    ["floor", "床"],
    ["ceiling", "天井"],
    ["corner", "角"],
    ["fridge", "冷蔵庫"],
    ["microwave", "電子レンジ"],
    ["stove", "コンロ"],
    ["sink", "流し台"],
    ["washing machine", "洗濯機"],
    ["hanger", "ハンガー"],
    ["laundry basket", "洗濯かご"],
    ["trash bag", "ごみ袋"],
    ["tissue", "ティッシュ"],
    ["remote", "リモコン"],
    ["outlet", "コンセント"],
    ["charger", "充電器"],
    ["smartphone", "スマートフォン"],
    ["battery", "バッテリー"],
    ["cable", "ケーブル"],
    ["screen", "画面"],
    ["keyboard", "キーボード"],
    ["mouse", "マウス"],
    ["browser", "ブラウザ"],
    ["app", "アプリ"],
    ["password", "パスワード"],
    ["Wi-Fi", "Wi-Fi"],
    ["signal", "電波"],
    ["download", "ダウンロードする"],
    ["upload", "アップロードする"],
    ["click", "クリックする"],
    ["tap", "タップする"],
    ["scan", "スキャンする"],
    ["photo", "写真"],
    ["video", "動画"],
    ["pharmacy", "薬局"],
    ["medicine", "薬"],
    ["headache", "頭痛"],
    ["fever", "熱"],
    ["cough", "せき"],
    ["cold", "風邪"],
    ["allergy", "アレルギー"],
    ["bandage", "ばんそうこう"],
    ["emergency", "緊急事態"],
    ["fire", "火事"],
    ["exit sign", "非常口の表示"],
    ["lost and found", "忘れ物係"],
    ["station", "駅"],
    ["stop", "停留所 / 止まる"],
    ["platform", "ホーム"],
    ["ticket gate", "改札"],
    ["crosswalk", "横断歩道"],
    ["traffic light", "信号"],
    ["elevator", "エレベーター"],
    ["escalator", "エスカレーター"],
    ["stairs", "階段"],
    ["entrance fee", "入場料"],
    ["fare", "運賃"]
  ])));

const intermediateWords = buildEntries([
  ["reservation", "予約"],
  ["passport", "パスポート"],
  ["luggage", "荷物"],
  ["suitcase", "スーツケース"],
  ["boarding pass", "搭乗券"],
  ["departure", "出発"],
  ["arrival", "到着"],
  ["delay", "遅延"],
  ["traffic", "交通状況"],
  ["route", "経路"],
  ["destination", "目的地"],
  ["direction", "方向"],
  ["entrance", "入口"],
  ["exit", "出口"],
  ["subway", "地下鉄"],
  ["schedule", "予定"],
  ["trip", "旅行"],
  ["journey", "旅"],
  ["cancel", "取り消す"],
  ["confirm", "確認する"],
  ["transfer", "乗り換え"],
  ["laundry", "洗濯"],
  ["detergent", "洗剤"],
  ["trash", "ごみ"],
  ["recycle", "再利用する"],
  ["repair", "修理する"],
  ["replace", "交換する"],
  ["organize", "整理する"],
  ["prepare", "準備する"],
  ["heat", "温める"],
  ["freeze", "凍らせる"],
  ["boil", "ゆでる"],
  ["fry", "焼く / 揚げる"],
  ["bake", "焼く"],
  ["mix", "混ぜる"],
  ["pour", "注ぐ"],
  ["decorate", "飾る"],
  ["invite", "招待する"],
  ["host", "主催する"],
  ["relax", "くつろぐ"],
  ["stretch", "伸ばす"],
  ["exercise", "運動する"],
  ["message", "メッセージ"],
  ["reply", "返信する"],
  ["respond", "応答する"],
  ["explain", "説明する"],
  ["describe", "説明する"],
  ["mention", "言及する"],
  ["repeat", "繰り返す"],
  ["pronounce", "発音する"],
  ["translate", "翻訳する"],
  ["introduce", "紹介する"],
  ["greet", "あいさつする"],
  ["apologize", "謝る"],
  ["forgive", "許す"],
  ["promise", "約束する"],
  ["suggest", "提案する"],
  ["recommend", "おすすめする"],
  ["agree", "同意する"],
  ["disagree", "反対する"],
  ["argue", "議論する"],
  ["discuss", "話し合う"],
  ["complain", "不満を言う"],
  ["warn", "警告する"],
  ["advise", "助言する"],
  ["encourage", "励ます"],
  ["mood", "気分"],
  ["emotion", "感情"],
  ["impression", "印象"],
  ["opinion", "意見"],
  ["choice", "選択"],
  ["reason", "理由"],
  ["result", "結果"],
  ["surprised", "驚いた"],
  ["nervous", "緊張した"],
  ["embarrassed", "恥ずかしい"],
  ["relieved", "ほっとした"],
  ["curious", "興味がある"],
  ["comfortable", "快適な"],
  ["confident", "自信がある"],
  ["honest", "正直な"],
  ["polite", "丁寧な"],
  ["serious", "真面目な"],
  ["actually", "実は"],
  ["probably", "たぶん"],
  ["perhaps", "もしかすると"],
  ["exactly", "正確に / まさに"],
  ["especially", "特に"],
  ["instead", "代わりに"],
  ["otherwise", "さもないと / ほかの場合は"],
  ["therefore", "したがって"],
  ["however", "しかしながら"],
  ["meanwhile", "その間に"],
  ["recently", "最近"],
  ["currently", "現在"],
  ["finally", "ついに / 最後に"],
  ["suddenly", "突然"],
  ["quietly", "静かに"],
  ["carefully", "注意深く"],
  ["luckily", "幸運にも"],
  ["unfortunately", "残念ながら"],
  ["nearly", "ほとんど / もう少しで"],
  ["exact", "正確な"],
  ["similar", "似ている"],
  ["common", "よくある / 一般的な"],
  ["local", "地元の"],
  ["public", "公共の"],
  ["private", "私的な"],
  ["traditional", "伝統的な"],
  ["modern", "現代的な"],
  ["famous", "有名な"],
  ["popular", "人気のある"],
  ["useful", "役に立つ"],
  ["convenient", "便利な"],
  ["necessary", "必要な"],
  ["safe", "安全な"],
  ["dangerous", "危険な"],
  ["crowded", "混んでいる"],
  ["quiet", "静かな"],
  ["available", "利用できる / 空いている"],
  ["worth", "価値がある"],
  ["memory", "記憶"],
  ["habit", "習慣"],
  ["experience", "経験"],
  ["skill", "技能"],
  ["knowledge", "知識"],
  ["culture", "文化"],
  ["custom", "習慣 / 風習"],
  ["relationship", "関係"],
  ["situation", "状況"],
  ["environment", "環境"],
  ["conversation", "会話"],
  ["topic", "話題"],
  ["example", "例"],
  ["sentence", "文"],
  ["paragraph", "段落"],
  ["article", "記事"],
  ["notice", "掲示 / 気づく"],
  ["announcement", "案内放送 / 発表"],
  ["instruction", "指示 / 説明"],
  ["warning", "警告"],
  ["permission", "許可"],
  ["invitation", "招待"],
  ["celebrate", "祝う"],
  ["avoid", "避ける"],
  ["borrow", "借りる"],
  ["lend", "貸す"],
  ["return home", "帰宅する"],
  ["arrange", "手配する / 整える"],
  ["contact", "連絡する / 連絡"],
  ["share", "共有する"],
  ["save", "保存する / 節約する"],
  ["delete", "削除する"],
  ["compare", "比較する"]
]);

const advancedWords = buildEntries([
  ["perspective", "視点"],
  ["option", "選択肢"],
  ["evidence", "証拠"],
  ["assumption", "前提"],
  ["context", "文脈"],
  ["strategy", "戦略"],
  ["approach", "やり方"],
  ["balance", "バランス"],
  ["priority", "優先事項"],
  ["outcome", "結果"],
  ["impact", "影響"],
  ["challenge", "課題"],
  ["opportunity", "機会"],
  ["solution", "解決策"],
  ["concern", "懸念"],
  ["confusion", "混乱"],
  ["clarity", "明確さ"],
  ["detail", "詳細"],
  ["summary", "要約"],
  ["argument", "主張"],
  ["analysis", "分析"],
  ["comparison", "比較"],
  ["contrast", "対比"],
  ["conclusion", "結論"],
  ["possibility", "可能性"],
  ["probability", "確率"],
  ["advantage", "利点"],
  ["disadvantage", "欠点"],
  ["consequence", "結果"],
  ["principle", "原則"],
  ["policy", "方針"],
  ["process", "過程"],
  ["progress", "進歩"],
  ["insight", "洞察"],
  ["judgment", "判断"],
  ["decision", "決定"],
  ["alternative", "代替案"],
  ["complexity", "複雑さ"],
  ["efficiency", "効率"],
  ["consistency", "一貫性"],
  ["flexibility", "柔軟性"],
  ["significance", "重要性"],
  ["persuade", "説得する"],
  ["justify", "正当化する"],
  ["evaluate", "評価する"],
  ["interpret", "解釈する"],
  ["demonstrate", "示す"],
  ["highlight", "強調する"],
  ["clarify", "明確にする"],
  ["assess", "査定する"],
  ["consider", "検討する"],
  ["recognize", "認識する"],
  ["estimate", "見積もる"],
  ["negotiate", "交渉する"],
  ["resolve", "解決する"],
  ["distinguish", "区別する"],
  ["specific", "具体的な"],
  ["abstract", "抽象的な"],
  ["logical", "論理的な"],
  ["practical", "実用的な"],
  ["realistic", "現実的な"],
  ["interpretation", "解釈"],
  ["framework", "枠組み"],
  ["criterion", "基準"],
  ["variable", "変数 / 要因"],
  ["factor", "要因"],
  ["trend", "傾向"],
  ["pattern", "パターン / 傾向"],
  ["phenomenon", "現象"],
  ["hypothesis", "仮説"],
  ["implication", "含意 / 影響"],
  ["consensus", "合意"],
  ["controversy", "論争"],
  ["objection", "異議"],
  ["rationale", "根拠"],
  ["credibility", "信頼性"],
  ["reliability", "信頼できること"],
  ["validity", "妥当性"],
  ["limitation", "限界"],
  ["scope", "範囲"],
  ["constraint", "制約"],
  ["trade-off", "両立しにくい関係"],
  ["uncertainty", "不確実性"],
  ["likelihood", "可能性の高さ"],
  ["tendency", "傾向"],
  ["bias", "偏り / 先入観"],
  ["prejudice", "偏見"],
  ["motivation", "動機"],
  ["intention", "意図"],
  ["perception", "認識"],
  ["awareness", "認識 / 意識"],
  ["capacity", "能力 / 容量"],
  ["capability", "遂行能力"],
  ["competence", "力量"],
  ["adaptability", "適応力"],
  ["resilience", "回復力"],
  ["stability", "安定性"],
  ["sustainability", "持続可能性"],
  ["effort", "努力"],
  ["achievement", "達成"],
  ["comprehensive", "包括的な"],
  ["subtle", "微妙な / 繊細な"],
  ["implicit", "暗黙の"],
  ["explicit", "明示的な"],
  ["objective", "客観的な / 目的"],
  ["subjective", "主観的な"],
  ["neutral", "中立の"],
  ["relevant", "関連のある"],
  ["appropriate", "適切な"],
  ["accurate", "正確な"],
  ["precise", "厳密な"],
  ["thorough", "徹底的な"],
  ["critical", "重大な / 批判的な"],
  ["fundamental", "根本的な"],
  ["essential", "不可欠な"],
  ["prominent", "著名な / 目立つ"],
  ["inevitable", "避けられない"],
  ["allocate", "割り当てる"],
  ["derive", "導き出す"],
  ["infer", "推測する"],
  ["examine", "詳しく調べる"],
  ["compile", "まとめる / 編集する"],
  ["formulate", "組み立てる"],
  ["articulate", "明確に言葉で表す"],
  ["convey", "伝える"],
  ["enhance", "高める"],
  ["diminish", "弱める / 減らす"],
  ["anticipate", "予測する"],
  ["prioritize", "優先する"]
]);

const businessWords = buildEntries([
  ["meeting", "会議"],
  ["agenda", "議題"],
  ["minutes", "議事録"],
  ["deadline", "締め切り"],
  ["proposal", "提案"],
  ["contract", "契約"],
  ["invoice", "請求書"],
  ["estimate", "見積もり"],
  ["budget", "予算"],
  ["cost", "費用"],
  ["expense", "経費"],
  ["profit", "利益"],
  ["revenue", "売上"],
  ["client", "顧客"],
  ["vendor", "取引先"],
  ["stakeholder", "関係者"],
  ["department", "部署"],
  ["staff", "スタッフ"],
  ["manager", "管理者"],
  ["leader", "リーダー"],
  ["task", "タスク"],
  ["project", "プロジェクト"],
  ["scope", "範囲"],
  ["timeline", "日程"],
  ["milestone", "節目"],
  ["deliverable", "成果物"],
  ["update", "進捗報告"],
  ["report", "報告書"],
  ["feedback", "意見"],
  ["request", "依頼"],
  ["approval", "承認"],
  ["review", "確認"],
  ["revision", "修正版"],
  ["draft", "下書き"],
  ["version", "版"],
  ["figure", "数値"],
  ["data", "データ"],
  ["forecast", "予測"],
  ["target", "目標"],
  ["resource", "資源"],
  ["risk", "リスク"],
  ["ownership", "担当責任"],
  ["coordination", "調整"],
  ["follow-up", "フォロー"],
  ["delivery", "納品"],
  ["launch", "開始"],
  ["implementation", "実装"],
  ["maintenance", "保守"],
  ["presentation", "発表"],
  ["attachment", "添付ファイル"],
  ["quarter", "四半期"],
  ["fiscal year", "会計年度"],
  ["earnings", "利益 / 収益"],
  ["margin", "利益率 / 余白"],
  ["turnover", "売上高 / 離職率"],
  ["cash flow", "資金繰り"],
  ["asset", "資産"],
  ["liability", "負債"],
  ["equity", "自己資本"],
  ["procurement", "調達"],
  ["inventory", "在庫"],
  ["shipment", "出荷"],
  ["warehouse", "倉庫"],
  ["logistics", "物流"],
  ["compliance", "法令順守"],
  ["regulation", "規制"],
  ["confidentiality", "機密保持"],
  ["disclosure", "開示"],
  ["partnership", "提携"],
  ["subsidiary", "子会社"],
  ["head office", "本社"],
  ["branch office", "支店"],
  ["headcount", "人員数"],
  ["recruitment", "採用"],
  ["interview", "面接"],
  ["onboarding", "入社時研修 / 受け入れ"],
  ["training", "研修"],
  ["evaluation", "評価"],
  ["promotion", "昇進 / 販促"],
  ["compensation", "報酬 / 補償"],
  ["salary", "給与"],
  ["bonus", "賞与"],
  ["benefit", "福利厚生 / 利点"],
  ["leave", "休暇"],
  ["overtime", "残業"],
  ["attendance", "出勤状況"],
  ["productivity", "生産性"],
  ["workflow", "業務の流れ"],
  ["procedure", "手順"],
  ["guideline", "指針"],
  ["manual", "マニュアル"],
  ["documentation", "文書化資料"],
  ["requirement", "要件"],
  ["specification", "仕様"],
  ["roadmap", "計画表"],
  ["backlog", "未処理案件"],
  ["issue", "課題 / 問題"],
  ["bug", "不具合"],
  ["testing", "テスト"],
  ["deployment", "配備 / リリース"],
  ["renewal", "更新"],
  ["negotiation", "交渉"],
  ["quotation", "見積書"],
  ["purchase order", "発注書"],
  ["payment terms", "支払条件"],
  ["due date", "支払期限 / 納期"],
  ["approval flow", "承認フロー"],
  ["escalation", "上位報告 / エスカレーション"],
  ["summary", "要約"],
  ["action item", "対応事項"],
  ["next step", "次の対応"],
  ["attendee", "出席者"],
  ["chairperson", "議長"],
  ["conference room", "会議室"],
  ["web conference", "オンライン会議"],
  ["mute", "ミュート"],
  ["screen sharing", "画面共有"],
  ["network issue", "通信トラブル"],
  ["availability", "空き状況"],
  ["reschedule", "日程変更する"],
  ["tentative", "仮の / 暫定の"]
]);

const travelWords = buildEntries([
  ["airport", "空港"],
  ["terminal", "ターミナル"],
  ["boarding gate", "搭乗口"],
  ["security check", "保安検査"],
  ["customs", "税関"],
  ["immigration", "入国審査"],
  ["arrival hall", "到着ロビー"],
  ["departure board", "出発案内板"],
  ["ticket counter", "チケット売り場"],
  ["platform number", "ホーム番号"],
  ["train line", "路線"],
  ["one-way ticket", "片道切符"],
  ["round-trip ticket", "往復切符"],
  ["seat reservation", "座席予約"],
  ["transfer station", "乗換駅"],
  ["taxi stand", "タクシー乗り場"],
  ["intersection", "交差点"],
  ["traffic light", "信号"],
  ["landmark", "目印"],
  ["distance", "距離"],
  ["front desk", "フロント"],
  ["check-in", "チェックイン"],
  ["check-out", "チェックアウト"],
  ["room key", "部屋の鍵"],
  ["single room", "シングルルーム"],
  ["double room", "ダブルルーム"],
  ["twin room", "ツインルーム"],
  ["view", "眺め"],
  ["luggage storage", "荷物預かり"],
  ["museum", "博物館"],
  ["temple", "寺"],
  ["shrine", "神社"],
  ["admission fee", "入場料"],
  ["souvenir", "お土産"],
  ["guidebook", "ガイドブック"],
  ["tourist spot", "観光地"],
  ["viewpoint", "展望スポット"],
  ["specialty", "名物"],
  ["ingredient", "材料"],
  ["spicy", "辛い"],
  ["mild", "辛くない"],
  ["dessert", "デザート"],
  ["service charge", "サービス料"],
  ["tip", "チップ"],
  ["cashier", "レジ"],
  ["clinic", "診療所"],
  ["injury", "けが"],
  ["emergency", "緊急事態"],
  ["police station", "警察署"],
  ["embassy", "大使館"],
  ["visa", "ビザ"],
  ["travel insurance", "旅行保険"],
  ["passport control", "入国審査"],
  ["baggage claim", "手荷物受取所"],
  ["carry-on bag", "機内持ち込み手荷物"],
  ["checked baggage", "預け荷物"],
  ["window seat", "窓側席"],
  ["aisle seat", "通路側席"],
  ["delayed flight", "遅延便"],
  ["connecting flight", "乗り継ぎ便"],
  ["boarding time", "搭乗時刻"],
  ["departure gate", "出発ゲート"],
  ["arrival time", "到着時刻"],
  ["bus stop", "バス停"],
  ["train station", "鉄道駅"],
  ["subway station", "地下鉄駅"],
  ["fare adjustment", "運賃精算"],
  ["rental car", "レンタカー"],
  ["parking lot", "駐車場"],
  ["highway", "高速道路"],
  ["street corner", "街角"],
  ["pedestrian crossing", "歩行者横断路"],
  ["city center", "市内中心部"],
  ["old town", "旧市街"],
  ["district", "地区"],
  ["map", "地図"],
  ["navigation app", "地図アプリ"],
  ["hostel", "ホステル"],
  ["guesthouse", "ゲストハウス"],
  ["vacancy", "空室"],
  ["non-smoking room", "禁煙室"],
  ["smoking room", "喫煙室"],
  ["breakfast included", "朝食付き"],
  ["late check-out", "レイトチェックアウト"],
  ["wake-up call", "モーニングコール"],
  ["room service", "ルームサービス"],
  ["laundry service", "ランドリーサービス"],
  ["restaurant", "レストラン"],
  ["menu", "メニュー"],
  ["set meal", "定食"],
  ["vegetarian", "菜食主義者向け"],
  ["allergy-friendly", "アレルギー対応の"],
  ["bottled water", "ボトル入りの水"],
  ["tap water", "水道水"],
  ["portion", "一人前 / 量"],
  ["reservation number", "予約番号"],
  ["sold out", "売り切れ"],
  ["line", "線 / 列 / 行"],
  ["ticket office", "切符売り場"],
  ["one-day pass", "一日乗車券"],
  ["coin locker", "コインロッカー"],
  ["restroom", "化粧室"],
  ["elevator hall", "エレベーターホール"],
  ["stairs exit", "階段出口"],
  ["tour guide", "ツアーガイド"],
  ["audio guide", "音声ガイド"],
  ["exhibition", "展示"],
  ["temple grounds", "寺院の境内"],
  ["observation deck", "展望台"],
  ["scenery", "景色"],
  ["sunset", "夕焼け / 日没"],
  ["local dish", "郷土料理"],
  ["street food", "屋台料理"],
  ["bill split", "割り勘"],
  ["currency exchange", "両替"],
  ["ATM fee", "ATM手数料"],
  ["lost property", "遺失物"],
  ["travel adapter", "変換プラグ"],
  ["charging station", "充電スポット"],
  ["first aid", "応急手当"],
  ["prescription", "処方箋"],
  ["travel clinic", "旅行者向け診療所"]
]);

function pickEntries(source, englishList) {
  const wanted = new Set(englishList.map((item) => item.toLowerCase()));
  return source.filter(({ english }) => wanted.has(english.toLowerCase()));
}

const basicWordsExpanded = dedupeEntries([
  ...beginnerWords,
  ...pickEntries(intermediateWords, [
    "prepare",
    "organize",
    "exercise",
    "message",
    "reply",
    "respond",
    "explain",
    "describe",
    "repeat",
    "pronounce",
    "translate",
    "introduce",
    "greet",
    "apologize",
    "forgive",
    "promise",
    "suggest",
    "recommend",
    "agree",
    "disagree",
    "discuss",
    "complain",
    "warn",
    "advise",
    "encourage",
    "mood",
    "emotion",
    "impression",
    "opinion",
    "choice",
    "reason",
    "result",
    "surprised",
    "nervous",
    "embarrassed",
    "relieved",
    "curious",
    "comfortable",
    "confident",
    "honest",
    "polite",
    "serious",
    "actually",
    "probably",
    "perhaps",
    "exactly",
    "especially",
    "instead",
    "however",
    "recently",
    "currently",
    "finally",
    "suddenly",
    "carefully",
    "luckily",
    "nearly",
    "exact",
    "similar",
    "common",
    "local",
    "public",
    "private",
    "traditional",
    "modern",
    "famous",
    "popular",
    "useful",
    "convenient",
    "necessary",
    "safe",
    "dangerous",
    "crowded",
    "quiet",
    "available",
    "worth",
    "memory",
    "habit",
    "experience",
    "skill",
    "knowledge",
    "culture",
    "relationship",
    "situation",
    "environment",
    "conversation",
    "topic",
    "example",
    "sentence",
    "notice",
    "announcement",
    "instruction",
    "permission",
    "invitation",
    "celebrate",
    "avoid",
    "borrow",
    "lend",
    "arrange",
    "contact",
    "share",
    "save",
    "delete",
    "compare"
  ]),
  ...buildEntries([
    ["math", "数学"],
    ["science", "理科"],
    ["history", "歴史"],
    ["music", "音楽"],
    ["art", "美術"],
    ["physical education", "体育"],
    ["club activity", "部活動"],
    ["homework", "宿題"],
    ["test score", "テストの点数"],
    ["summer vacation", "夏休み"],
    ["winter vacation", "冬休み"],
    ["spring break", "春休み"],
    ["classroom", "教室"],
    ["hallway", "廊下"],
    ["playground", "校庭"],
    ["library card", "図書カード"],
    ["notebook", "ノート"],
    ["eraser", "消しゴム"],
    ["ruler", "定規"],
    ["glue", "のり"],
    ["scissors", "はさみ"],
    ["crayon", "クレヨン"],
    ["dictionary", "辞書"],
    ["calendar", "カレンダー"],
    ["watch", "腕時計"],
    ["alarm", "目覚まし"],
    ["calendar app", "予定アプリ"],
    ["birthday party", "誕生日会"],
    ["picnic", "ピクニック"],
    ["festival", "お祭り"],
    ["vacuum", "掃除機"],
    ["mop", "モップ"],
    ["clean up", "片づける"],
    ["wash up", "食器を洗う"],
    ["hang up", "掛ける / 電話を切る"],
    ["fold", "たたむ"],
    ["pack", "荷造りする"],
    ["unpack", "荷ほどきする"],
    ["feed", "えさをやる"],
    ["pet", "ペット"],
    ["hamster", "ハムスター"],
    ["rabbit", "うさぎ"],
    ["duck", "あひる"],
    ["farm", "農場"],
    ["garden", "庭"],
    ["plant", "植物 / 植える"],
    ["flower", "花"],
    ["leaf", "葉"],
    ["branch", "枝"],
    ["grass", "草"],
    ["river", "川"],
    ["lake", "湖"],
    ["beach", "浜辺"],
    ["mountain", "山"],
    ["forest", "森"],
    ["bridge", "橋"],
    ["town", "町"],
    ["village", "村"],
    ["capital city", "首都"],
    ["country side", "田舎"],
    ["stationery", "文房具"],
    ["pencil case", "筆箱"],
    ["textbook", "教科書"],
    ["worksheet", "プリント"],
    ["lesson", "授業"],
    ["question", "質問 / 問題"],
    ["answer", "答え"],
    ["mistake", "間違い"],
    ["practice", "練習"],
    ["review", "復習 / 確認"],
    ["preview", "予習"],
    ["club room", "部室"],
    ["shoe box", "下駄箱"],
    ["uniform", "制服"],
    ["gym shoes", "上履き / 体育館シューズ"],
    ["lunch box", "お弁当"],
    ["cafeteria", "食堂"],
    ["break time", "休み時間"],
    ["after school", "放課後"],
    ["weekdays", "平日"],
    ["allowance", "おこづかい"],
    ["part-time job", "アルバイト"],
    ["bank account", "銀行口座"],
    ["piggy bank", "貯金箱"],
    ["wallet chain", "財布チェーン"],
    ["favorite", "お気に入りのもの"],
    ["hobby", "趣味"],
    ["movie", "映画"],
    ["drama", "ドラマ"],
    ["comic", "漫画"],
    ["novel", "小説"],
    ["magazine", "雑誌"],
    ["newspaper", "新聞"],
    ["radio", "ラジオ"],
    ["speaker", "スピーカー"],
    ["headphones", "ヘッドホン"],
    ["microphone", "マイク"],
    ["game console", "ゲーム機"],
    ["controller", "コントローラー"],
    ["score", "得点 / 点数"],
    ["winner", "勝者"],
    ["loser", "敗者"],
    ["teamwork", "チームワーク"],
    ["cheer", "応援する"],
    ["practice match", "練習試合"],
    ["raincoat", "レインコート"],
    ["boots", "長靴 / ブーツ"],
    ["sneakers", "スニーカー"],
    ["slippers", "スリッパ"],
    ["coat", "コート"],
    ["jacket", "上着"],
    ["sweater", "セーター"],
    ["hoodie", "パーカー"],
    ["pants", "ズボン"],
    ["skirt", "スカート"],
    ["socks", "靴下"],
    ["gloves", "手袋"],
    ["scarf", "マフラー"],
    ["cap", "帽子"],
    ["umbrella stand", "傘立て"],
    ["season", "季節"],
    ["temperature", "気温"],
    ["forecast", "天気予報"],
    ["earthquake", "地震"],
    ["typhoon", "台風"],
    ["power outage", "停電"],
    ["internet", "インターネット"],
    ["search", "検索する"],
    ["login", "ログインする"],
    ["logout", "ログアウトする"],
    ["profile", "プロフィール"],
    ["nickname", "ニックネーム"],
    ["setting", "設定"],
    ["notification", "通知"],
    ["privacy", "プライバシー"],
    ["shortcut", "近道 / ショートカット"],
    ["battery life", "電池の持ち"],
    ["charging cable", "充電ケーブル"],
    ["volume", "音量"],
    ["brightness", "明るさ"],
    ["screenshot", "画面の保存"],
    ["refresh", "再読み込みする"],
    ["update", "更新する"],
    ["comment", "コメント"],
    ["post", "投稿する / 投稿"],
    ["follow", "フォローする"],
    ["block", "ブロックする"],
    ["report abuse", "迷惑行為を通報する"],
    ["health", "健康"],
    ["stomachache", "腹痛"],
    ["toothache", "歯痛"],
    ["sore throat", "のどの痛み"],
    ["runny nose", "鼻水"],
    ["feeling", "気分"],
    ["healthy", "健康な"],
    ["sleepy", "眠い"],
    ["tired", "疲れた"],
    ["hungry", "お腹が空いた"],
    ["thirsty", "のどが渇いた"],
    ["full from eating", "お腹いっぱいの"],
    ["medicine box", "薬箱"],
    ["thermometer", "体温計"],
    ["ice pack", "冷却シート / 保冷剤"],
    ["cough drop", "のど飴"],
    ["appointment", "予約 / 約束"],
    ["plan", "予定 / 計画"],
    ["promise time", "待ち合わせ時間"],
    ["free time", "ひまな時間"],
    ["hurry", "急ぐ"],
    ["wait a moment", "少し待つ"],
    ["be late", "遅れる"],
    ["on time", "時間どおりに"],
    ["in a hurry", "急いで"],
    ["take a break", "休憩する"],
    ["meet up", "会う"],
    ["hang out", "遊ぶ"],
    ["go shopping", "買い物に行く"],
    ["take a walk", "散歩する"],
    ["go home", "家に帰る"],
    ["come back", "戻る"],
    ["bring", "持ってくる"],
    ["carry", "運ぶ"],
    ["send", "送る"],
    ["receive", "受け取る"],
    ["show", "見せる"],
    ["teach", "教える"],
    ["learn", "学ぶ"],
    ["remember", "覚えている"],
    ["forget", "忘れる"],
    ["choose", "選ぶ"],
    ["finish", "終える"],
    ["start", "始める"],
    ["begin", "始まる / 始める"],
    ["continue", "続ける"],
    ["stop doing", "やめる"],
    ["open", "開ける / 開く"],
    ["close", "閉める / 閉じる"],
    ["turn on", "つける"],
    ["turn off", "消す"],
    ["pick up", "拾う / 取りに行く"],
    ["put down", "置く"],
    ["wear", "身につける"],
    ["try", "試す"],
    ["enjoy", "楽しむ"],
    ["laugh", "笑う"],
    ["cry", "泣く"],
    ["worry", "心配する"],
    ["hope", "願う"],
    ["dream", "夢"],
    ["future", "未来"],
    ["past", "過去"],
    ["present", "現在 / 贈り物"],
    ["week", "週"],
    ["month", "月"],
    ["yearly", "毎年の"],
    ["daily", "毎日の"],
    ["weekly", "毎週の"],
    ["monthly", "毎月の"],
    ["favorite subject", "好きな教科"],
    ["school trip", "修学旅行"],
    ["sports day", "運動会"],
    ["culture festival", "文化祭"],
    ["music club", "音楽部"],
    ["art club", "美術部"],
    ["school bag", "通学かばん"],
    ["lunch break", "昼休み"],
    ["best friend", "親友"],
    ["new student", "転校生 / 新入生"],
    ["school nurse", "保健の先生"],
    ["class leader", "学級委員"],
    ["group work", "グループ活動"],
    ["study note", "勉強ノート"],
    ["practice test", "練習テスト"]
  ])
]);

const practicalWords = dedupeEntries([
  ...intermediateWords,
  ...advancedWords,
  ...pickEntries(beginnerWords, [
    "price",
    "cost",
    "payment",
    "cash",
    "change",
    "receipt",
    "credit card",
    "debit card",
    "discount",
    "customer",
    "store",
    "market",
    "package",
    "delivery",
    "address",
    "zip code",
    "post office",
    "check",
    "key",
    "remote",
    "outlet",
    "charger",
    "smartphone",
    "browser",
    "password",
    "signal",
    "download",
    "upload",
    "pharmacy",
    "medicine",
    "emergency",
    "fire",
    "station",
    "platform",
    "crosswalk",
    "traffic light",
    "elevator",
    "escalator",
    "stairs",
    "fare",
    "appointment",
    "notification",
    "privacy",
    "search",
    "profile",
    "setting",
    "health",
    "forecast",
    "power outage",
    "internet"
  ]),
  ...buildEntries([
    ["administration", "事務手続き"],
    ["application form", "申込書"],
    ["document", "書類"],
    ["identification", "身分証明"],
    ["reference", "参照 / 参考情報"],
    ["certificate", "証明書"],
    ["official", "公式の / 公務員"],
    ["citizen", "市民"],
    ["resident", "居住者"],
    ["household", "世帯 / 家庭"],
    ["community", "地域社会"],
    ["public office", "役所"],
    ["city hall", "市役所"],
    ["ward office", "区役所"],
    ["application deadline", "申込締切"],
    ["confirmation number", "確認番号"],
    ["reservation number", "予約番号"],
    ["queue", "列 / 順番待ち"],
    ["waiting area", "待合スペース"],
    ["counter service", "窓口対応"],
    ["consultation", "相談"],
    ["inquiry", "問い合わせ"],
    ["support desk", "サポート窓口"],
    ["trouble", "トラブル"],
    ["issue report", "問題報告"],
    ["lost item", "落とし物"],
    ["found item", "拾得物"],
    ["claim ticket", "引換券"],
    ["refund policy", "返金方針"],
    ["exchange policy", "交換方針"],
    ["warranty", "保証"],
    ["service center", "サービスセンター"],
    ["repair shop", "修理店"],
    ["booking", "予約"],
    ["seat", "座席"],
    ["standing room", "立ち席"],
    ["priority seat", "優先席"],
    ["announcement board", "案内掲示板"],
    ["information desk", "案内所"],
    ["route map", "路線図"],
    ["detour", "迂回路"],
    ["construction", "工事"],
    ["delay notice", "遅延案内"],
    ["suspension", "運休 / 停止"],
    ["fare gate", "改札機"],
    ["commuter pass", "定期券"],
    ["balance check", "残高確認"],
    ["top up", "チャージする"],
    ["refund machine", "払戻機"],
    ["drop off", "降ろす / 置く"],
    ["pick someone up", "迎えに行く"],
    ["entrance hall", "入口ホール"],
    ["exit sign", "出口表示"],
    ["slippery", "滑りやすい"],
    ["broken", "壊れた"],
    ["out of order", "故障中の"],
    ["occupied", "使用中の / ふさがっている"],
    ["vacant", "空いている"],
    ["crowd", "人混み"],
    ["shortcut route", "近道ルート"],
    ["appointment slot", "予約枠"],
    ["reschedule request", "日程変更依頼"],
    ["late fee", "延滞料金"],
    ["membership", "会員資格"],
    ["subscription", "定期契約"],
    ["renewal fee", "更新料"],
    ["cancellation fee", "取消料"],
    ["checklist", "確認項目一覧"],
    ["priority", "優先事項"],
    ["backup", "予備 / バックアップ"],
    ["storage", "保管 / ストレージ"],
    ["folder", "フォルダー"],
    ["file name", "ファイル名"],
    ["attachment limit", "添付上限"],
    ["password reset", "パスワード再設定"],
    ["verification code", "認証コード"],
    ["account lock", "アカウント停止"],
    ["temporary", "一時的な"],
    ["permanent", "恒久的な"],
    ["recommended", "推奨される"],
    ["optional", "任意の"],
    ["required", "必須の"],
    ["notice period", "予告期間"],
    ["opening hours", "営業時間"],
    ["closed day", "定休日"],
    ["peak time", "混雑時間帯"],
    ["discount period", "割引期間"],
    ["limited edition", "限定版"],
    ["sample", "見本 / 試供品"],
    ["ingredient list", "原材料一覧"],
    ["expiration date", "賞味期限 / 使用期限"],
    ["instruction manual", "取扱説明書"],
    ["safety guide", "安全案内"],
    ["privacy setting", "プライバシー設定"],
    ["usage history", "利用履歴"],
    ["learning record", "学習記録"],
    ["guest mode", "ゲストモード"],
    ["registered user", "登録ユーザー"],
    ["continue button", "続けるボタン"],
    ["reset option", "リセット項目"],
    ["progress summary", "進捗まとめ"],
    ["accuracy", "正答率"],
    ["attempt", "試行 / 回答回数"],
    ["skip", "スキップする"],
    ["review item", "見直し項目"],
    ["mistyped", "打ち間違えた"],
    ["pronunciation guide", "発音ガイド"],
    ["example sentence", "例文"],
    ["daily routine", "日課"],
    ["weekly plan", "週間予定"],
    ["monthly goal", "月間目標"],
    ["habit tracker", "習慣記録表"],
    ["learning plan", "学習計画"],
    ["study break", "学習休憩"],
    ["practice partner", "練習相手"],
    ["self introduction", "自己紹介"],
    ["small talk", "雑談"],
    ["follow question", "追加の質問"],
    ["main point", "要点"],
    ["key detail", "重要な詳細"],
    ["background", "背景"],
    ["basic idea", "基本的な考え"],
    ["common mistake", "よくある間違い"],
    ["natural expression", "自然な表現"],
    ["direct expression", "直接的な表現"],
    ["soft expression", "やわらかい表現"],
    ["clear answer", "明確な答え"],
    ["simple explanation", "簡潔な説明"],
    ["real example", "実例"],
    ["additional note", "補足"],
    ["daily use", "日常使用"],
    ["public place", "公共の場所"],
    ["shared space", "共有スペース"],
    ["indoor shoes", "室内履き"],
    ["carry case", "持ち運び用ケース"],
    ["folding umbrella", "折りたたみ傘"],
    ["tissue paper", "ティッシュペーパー"],
    ["wet wipes", "ウェットティッシュ"],
    ["reusable bag", "エコバッグ"],
    ["water bottle", "水筒"],
    ["charging spot", "充電できる場所"],
    ["quiet area", "静かな場所"],
    ["free seat", "空席"],
    ["shared table", "相席テーブル"],
    ["line break", "改行"],
    ["menu screen", "メニュー画面"],
    ["top page", "トップページ"],
    ["link", "リンク"],
    ["button", "ボタン"],
    ["notice message", "お知らせメッセージ"],
    ["guest account", "ゲスト利用"],
    ["saved progress", "保存済みの進捗"],
    ["learning content", "学習内容"],
    ["progress reset", "進捗リセット"],
    ["access code", "アクセスコード"],
    ["entry form", "入力フォーム"],
    ["service desk", "総合窓口"],
    ["pick-up service", "受け取りサービス"],
    ["return desk", "返却窓口"],
    ["temporary pass", "仮パス"],
    ["visiting hours", "受付時間 / 面会時間"],
    ["emergency contact", "緊急連絡先"],
    ["voice message", "留守番メッセージ"],
    ["auto reply", "自動返信"],
    ["call back", "折り返し電話する"],
    ["message history", "メッセージ履歴"],
    ["help center", "ヘルプセンター"],
    ["service notice", "サービス案内"],
    ["maintenance notice", "メンテナンス案内"],
    ["document check", "書類確認"],
    ["identity check", "本人確認"],
    ["user support", "利用者サポート"],
    ["learning goal", "学習目標"],
    ["study record", "学習記録"],
    ["review list", "見直し一覧"],
    ["error message", "エラーメッセージ"]
  ])
]);

const businessWordsExpanded = dedupeEntries([
  ...advancedWords,
  ...businessWords,
  ...pickEntries(intermediateWords, [
    "confirm",
    "organize",
    "prepare",
    "message",
    "reply",
    "respond",
    "explain",
    "describe",
    "mention",
    "repeat",
    "translate",
    "introduce",
    "promise",
    "suggest",
    "recommend",
    "agree",
    "disagree",
    "discuss",
    "complain",
    "warn",
    "advise",
    "encourage",
    "opinion",
    "reason",
    "result",
    "honest",
    "polite",
    "serious",
    "exactly",
    "therefore",
    "however",
    "currently",
    "available",
    "compare"
  ]),
  ...pickEntries(beginnerWords, [
    "price",
    "cost",
    "payment",
    "receipt",
    "delivery",
    "address",
    "browser",
    "password",
    "download",
    "upload",
    "search",
    "update",
    "comment",
    "post",
    "notification",
    "profile",
    "setting",
    "internet"
  ]),
  ...buildEntries([
    ["agreement", "合意 / 契約書"],
    ["amendment", "修正契約 / 修正事項"],
    ["contract term", "契約条件"],
    ["renewal notice", "更新通知"],
    ["termination", "終了 / 解約"],
    ["conflict", "対立 / 競合"],
    ["escalate", "上位に報告する"],
    ["coordinate", "調整する"],
    ["delegate", "任せる"],
    ["assign", "割り当てる"],
    ["ownership transfer", "担当移管"],
    ["handover", "引き継ぎ"],
    ["deliver", "納品する / 届ける"],
    ["ship", "出荷する"],
    ["approve", "承認する"],
    ["reject", "却下する"],
    ["revise", "修正する"],
    ["finalize", "最終確定する"],
    ["summarize", "要約する"],
    ["briefing", "説明会 / ブリーフィング"],
    ["agenda item", "議題項目"],
    ["discussion point", "検討事項"],
    ["key takeaway", "重要な持ち帰り事項"],
    ["decision maker", "決裁者"],
    ["approval line", "承認経路"],
    ["review cycle", "レビュー周期"],
    ["response time", "応答時間"],
    ["service level", "サービス水準"],
    ["turnaround time", "対応完了までの時間"],
    ["delivery date", "納品日"],
    ["payment date", "支払日"],
    ["billing address", "請求先住所"],
    ["account manager", "担当営業"],
    ["sales representative", "営業担当者"],
    ["procurement team", "調達チーム"],
    ["human resources", "人事部"],
    ["finance team", "経理 / 財務チーム"],
    ["operations team", "運用チーム"],
    ["support team", "サポートチーム"],
    ["product team", "製品チーム"],
    ["development team", "開発チーム"],
    ["quality assurance", "品質保証"],
    ["legal team", "法務チーム"],
    ["internal meeting", "社内会議"],
    ["client meeting", "顧客打ち合わせ"],
    ["kickoff meeting", "キックオフ会議"],
    ["status meeting", "進捗会議"],
    ["one-on-one", "1対1の面談"],
    ["performance review", "評価面談"],
    ["business trip", "出張"],
    ["expense claim", "経費精算申請"],
    ["reimbursement", "立替精算 / 払い戻し"],
    ["travel expense", "出張費"],
    ["daily allowance", "日当"],
    ["tax invoice", "適格請求書"],
    ["purchase request", "購買申請"],
    ["vendor list", "仕入先一覧"],
    ["supplier", "供給業者"],
    ["stock level", "在庫水準"],
    ["reorder", "再発注する"],
    ["lead time", "納期までの期間"],
    ["delivery schedule", "納品予定"],
    ["forecast accuracy", "予測精度"],
    ["sales target", "売上目標"],
    ["monthly report", "月次報告"],
    ["annual report", "年次報告"],
    ["performance", "業績 / パフォーマンス"],
    ["growth", "成長"],
    ["decline", "減少 / 落ち込み"],
    ["market share", "市場占有率"],
    ["competitor", "競合他社"],
    ["customer base", "顧客基盤"],
    ["user feedback", "利用者の声"],
    ["satisfaction", "満足度"],
    ["complaint handling", "苦情対応"],
    ["retention", "継続率 / 保持"],
    ["renewal rate", "更新率"],
    ["conversion", "成約 / 転換"],
    ["campaign", "キャンペーン"],
    ["promotion plan", "販促計画"],
    ["brand image", "ブランドイメージ"],
    ["presentation slide", "プレゼン資料"],
    ["speaker note", "発表メモ"],
    ["handout", "配布資料"],
    ["meeting room", "会議室"],
    ["conference link", "会議リンク"],
    ["participant", "参加者"],
    ["attendee list", "出席者一覧"],
    ["calendar invite", "招待予定"],
    ["time zone", "時間帯 / タイムゾーン"],
    ["mute button", "ミュートボタン"],
    ["camera on", "カメラオン"],
    ["camera off", "カメラオフ"],
    ["screen share", "画面共有"],
    ["recording", "録画"],
    ["connection issue", "接続トラブル"],
    ["follow-up email", "フォローアップメール"],
    ["draft email", "メール下書き"],
    ["subject line", "件名"],
    ["recipient", "宛先"],
    ["cc", "CC"],
    ["bcc", "BCC"],
    ["email thread", "メールのやり取り"],
    ["reply all", "全員に返信"],
    ["urgent", "緊急の"],
    ["high priority", "優先度が高い"],
    ["pending", "保留中の"],
    ["completed", "完了した"],
    ["in progress", "進行中の"],
    ["under review", "確認中の"],
    ["on hold", "保留の"],
    ["action required", "対応が必要"],
    ["optional field", "任意項目"],
    ["required field", "必須項目"],
    ["account status", "アカウント状況"],
    ["trial period", "試用期間"],
    ["subscription plan", "契約プラン"],
    ["billing cycle", "請求サイクル"],
    ["maintenance window", "保守時間帯"],
    ["downtime", "停止時間"],
    ["release note", "更新内容"],
    ["version history", "更新履歴"],
    ["user guide", "利用ガイド"],
    ["knowledge base", "ナレッジベース"],
    ["troubleshooting", "問題切り分け"],
    ["incident", "障害 / 事案"],
    ["resolution", "解決"],
    ["root cause", "根本原因"],
    ["preventive action", "再発防止策"],
    ["training session", "研修会"],
    ["check-in meeting", "定例確認会"],
    ["alignment", "認識合わせ"],
    ["expectation", "期待 / 想定"],
    ["deliverable list", "納品物一覧"],
    ["project plan", "プロジェクト計画"],
    ["change request", "変更依頼"],
    ["scope change", "仕様変更"],
    ["risk assessment", "リスク評価"],
    ["budget approval", "予算承認"],
    ["staffing", "人員配置"],
    ["resource plan", "要員計画"],
    ["training material", "研修資料"],
    ["meeting summary", "会議要約"],
    ["business objective", "事業目的"],
    ["quarterly goal", "四半期目標"],
    ["annual budget", "年間予算"],
    ["target audience", "対象顧客層"],
    ["sales pitch", "営業提案"],
    ["renewal proposal", "更新提案"],
    ["pricing plan", "料金体系"],
    ["discount rate", "割引率"],
    ["invoice number", "請求番号"],
    ["payment reminder", "支払催促"],
    ["late payment", "支払遅延"],
    ["bank transfer", "銀行振込"],
    ["expense limit", "経費上限"],
    ["approval request", "承認依頼"],
    ["company policy", "社内規程"],
    ["security policy", "セキュリティ方針"],
    ["access right", "アクセス権限"],
    ["confidential file", "機密ファイル"],
    ["data handling", "データ取扱い"],
    ["internal use", "社内利用"],
    ["external use", "社外利用"],
    ["support ticket", "問い合わせチケット"],
    ["case number", "案件番号"],
    ["response deadline", "回答期限"],
    ["working day", "営業日"],
    ["approval email", "承認メール"],
    ["business day", "営業日"],
    ["business impact", "業務への影響"],
    ["customer request", "顧客要望"],
    ["issue tracker", "課題管理表"],
    ["project owner", "案件責任者"],
    ["review comment", "レビューコメント"],
    ["comment thread", "コメントのやり取り"],
    ["approval status", "承認状況"],
    ["payment status", "支払状況"],
    ["delivery status", "納品状況"],
    ["updated file", "更新済みファイル"],
    ["shared folder", "共有フォルダー"],
    ["access request", "権限申請"],
    ["security review", "セキュリティ確認"],
    ["release schedule", "公開予定"],
    ["support request", "サポート依頼"],
    ["customer success", "顧客支援"],
    ["service contract", "業務委託契約"],
    ["billing information", "請求情報"],
    ["tax amount", "税額"],
    ["payment method", "支払方法"],
    ["unit price", "単価"],
    ["estimate request", "見積依頼"],
    ["quotation number", "見積番号"],
    ["invoice date", "請求日"],
    ["purchase history", "購買履歴"],
    ["monthly target", "月次目標"],
    ["sales result", "売上実績"],
    ["expense report", "経費報告"],
    ["attendance record", "勤怠記録"],
    ["paid leave", "有給休暇"],
    ["sick leave", "病気休暇"],
    ["training plan", "研修計画"],
    ["evaluation sheet", "評価シート"],
    ["team leader", "チームリーダー"],
    ["department head", "部門責任者"],
    ["business partner", "取引先"],
    ["proposal draft", "提案書の下書き"],
    ["meeting agenda", "会議の議題"],
    ["meeting note", "会議メモ"],
    ["action plan", "行動計画"]
  ])
]);

const travelWordsExpanded = dedupeEntries([
  ...travelWords,
  ...pickEntries(intermediateWords, [
    "reservation",
    "passport",
    "luggage",
    "suitcase",
    "boarding pass",
    "departure",
    "arrival",
    "delay",
    "traffic",
    "route",
    "destination",
    "direction",
    "entrance",
    "exit",
    "subway",
    "schedule",
    "trip",
    "journey",
    "confirm",
    "transfer"
  ]),
  ...pickEntries(beginnerWords, [
    "price",
    "payment",
    "cash",
    "change",
    "receipt",
    "customer",
    "store",
    "market",
    "mall",
    "basket",
    "cart",
    "size",
    "breakfast",
    "lunch",
    "dinner",
    "dessert",
    "salad",
    "rice",
    "bread",
    "fruit",
    "vegetable",
    "fish",
    "chicken",
    "beef",
    "pork",
    "juice",
    "tea",
    "coffee",
    "bottle",
    "cup",
    "glass",
    "plate",
    "spoon",
    "fork",
    "knife",
    "chopsticks",
    "napkin",
    "check",
    "key",
    "pillow",
    "blanket",
    "towel",
    "soap",
    "shampoo",
    "toothbrush",
    "dryer",
    "mirror",
    "fridge",
    "microwave",
    "outlet",
    "charger",
    "smartphone",
    "battery",
    "screen",
    "Wi-Fi",
    "signal",
    "photo",
    "video",
    "pharmacy",
    "medicine",
    "fever",
    "cough",
    "cold",
    "allergy",
    "emergency",
    "fire",
    "station",
    "platform",
    "ticket gate",
    "crosswalk",
    "traffic light",
    "elevator",
    "escalator",
    "stairs",
    "entrance fee",
    "fare",
    "map",
    "forecast",
    "umbrella stand",
    "beach",
    "mountain",
    "bridge",
    "town"
  ]),
  ...buildEntries([
    ["boarding zone", "搭乗ゾーン"],
    ["departure lobby", "出発ロビー"],
    ["arrival gate", "到着口"],
    ["immigration form", "入国カード"],
    ["customs declaration", "税関申告"],
    ["duty-free shop", "免税店"],
    ["airport shuttle", "空港シャトル"],
    ["airport lounge", "空港ラウンジ"],
    ["passport case", "パスポートケース"],
    ["luggage tag", "手荷物タグ"],
    ["overweight baggage", "超過手荷物"],
    ["fragile item", "壊れ物"],
    ["priority boarding", "優先搭乗"],
    ["boarding announcement", "搭乗案内"],
    ["flight number", "便名"],
    ["airline counter", "航空会社カウンター"],
    ["security line", "保安検査の列"],
    ["liquid restriction", "液体持込制限"],
    ["carry-on allowance", "機内持込許容量"],
    ["arrival delay", "到着遅延"],
    ["gate change", "ゲート変更"],
    ["missed flight", "乗り遅れ"],
    ["rebooking", "振替手配"],
    ["boarding area", "搭乗エリア"],
    ["seat belt sign", "シートベルト着用サイン"],
    ["overhead bin", "頭上収納棚"],
    ["in-flight meal", "機内食"],
    ["customs officer", "税関職員"],
    ["passport check", "旅券確認"],
    ["arrival card", "入国カード"],
    ["exit gate", "出口ゲート"],
    ["taxi driver", "タクシー運転手"],
    ["meter", "メーター"],
    ["shared ride", "相乗り"],
    ["drop-off point", "降車場所"],
    ["pick-up point", "乗車場所"],
    ["bus route", "バス路線"],
    ["bus terminal", "バスターミナル"],
    ["train schedule", "列車時刻表"],
    ["express train", "急行列車"],
    ["local train", "各駅停車"],
    ["last train", "終電"],
    ["first train", "始発"],
    ["ticket machine", "券売機"],
    ["ticket window", "切符窓口"],
    ["reserved seat", "指定席"],
    ["non-reserved seat", "自由席"],
    ["platform sign", "ホーム案内表示"],
    ["station staff", "駅員"],
    ["bus fare", "バス運賃"],
    ["tap card", "タッチ式乗車カード"],
    ["fare card", "交通系カード"],
    ["passenger", "乗客"],
    ["tour bus", "観光バス"],
    ["traffic jam", "渋滞"],
    ["narrow street", "狭い道"],
    ["one-way street", "一方通行"],
    ["pedestrian area", "歩行者エリア"],
    ["side street", "脇道"],
    ["downtown", "繁華街 / 中心街"],
    ["suburb", "郊外"],
    ["shopping district", "商店街"],
    ["tourist information center", "観光案内所"],
    ["city map", "市内地図"],
    ["walking distance", "徒歩圏内"],
    ["entrance ticket", "入場券"],
    ["advance ticket", "前売券"],
    ["sold-out ticket", "売切券"],
    ["guided tour", "案内付きツアー"],
    ["self-guided tour", "自由見学"],
    ["queue line", "待機列"],
    ["security guard", "警備員"],
    ["locker key", "ロッカーキー"],
    ["locker number", "ロッカー番号"],
    ["hotel lobby", "ホテルロビー"],
    ["guest room", "客室"],
    ["front office", "フロント業務"],
    ["concierge", "コンシェルジュ"],
    ["bell staff", "ベルスタッフ"],
    ["housekeeping", "客室清掃"],
    ["extra towel", "追加タオル"],
    ["extra pillow", "追加枕"],
    ["late arrival", "遅い到着"],
    ["early arrival", "早い到着"],
    ["room charge", "部屋料金"],
    ["city tax", "宿泊税"],
    ["deposit", "保証金"],
    ["passport copy", "パスポートのコピー"],
    ["room number", "部屋番号"],
    ["key card", "カードキー"],
    ["wake-up service", "モーニングコールサービス"],
    ["iron", "アイロン"],
    ["hanger rack", "ハンガーラック"],
    ["ice machine", "製氷機"],
    ["laundry room", "ランドリールーム"],
    ["vending machine", "自動販売機"],
    ["mini bar", "ミニバー"],
    ["shower room", "シャワールーム"],
    ["bathtub", "浴槽"],
    ["water pressure", "水圧"],
    ["air conditioning", "空調"],
    ["restaurant reservation", "レストラン予約"],
    ["table reservation", "席予約"],
    ["window table", "窓側の席"],
    ["counter seat", "カウンター席"],
    ["kids menu", "子ども向けメニュー"],
    ["drink menu", "ドリンクメニュー"],
    ["special menu", "おすすめメニュー"],
    ["house special", "看板料理"],
    ["vegetarian menu", "ベジタリアン向けメニュー"],
    ["gluten-free", "グルテンフリー"],
    ["extra spicy", "とても辛い"],
    ["less salt", "塩控えめ"],
    ["no ice", "氷なし"],
    ["hot drink", "温かい飲み物"],
    ["cold drink", "冷たい飲み物"],
    ["refill", "おかわり"],
    ["takeout", "持ち帰り"],
    ["to go", "持ち帰りで"],
    ["tableware", "食器類"],
    ["service included", "サービス料込み"],
    ["cash only", "現金のみ"],
    ["card accepted", "カード利用可"],
    ["currency", "通貨"],
    ["exchange rate", "為替レート"],
    ["small change", "小銭"],
    ["cash withdrawal", "現金引き出し"],
    ["foreign card", "海外発行カード"],
    ["blocked card", "使えないカード"],
    ["lost card", "紛失したカード"],
    ["travel wallet", "旅行用財布"],
    ["rainy day", "雨の日"],
    ["sunny spot", "日当たりのよい場所"],
    ["shade", "日陰"],
    ["crowded area", "混雑エリア"],
    ["quiet street", "静かな通り"],
    ["photo spot", "写真スポット"],
    ["famous place", "有名スポット"],
    ["local market", "地元の市場"],
    ["souvenir shop", "土産店"],
    ["opening time", "開店時間"],
    ["closing time", "閉店時間"],
    ["closed today", "本日休業"],
    ["admission line", "入場待ち列"],
    ["temple gate", "寺の門"],
    ["main hall", "本堂"],
    ["shrine office", "社務所"],
    ["observation area", "展望エリア"],
    ["viewing point", "見晴らし地点"],
    ["sunrise", "日の出"],
    ["weather warning", "気象警報"],
    ["light rain", "小雨"],
    ["heavy rain", "大雨"],
    ["strong wind", "強風"],
    ["slippery road", "滑りやすい道"],
    ["stairs entrance", "階段入口"],
    ["emergency exit", "非常口"],
    ["ambulance", "救急車"],
    ["hospital", "病院"],
    ["medical certificate", "診断書"],
    ["painkiller", "痛み止め"],
    ["stomach medicine", "胃薬"],
    ["cold medicine", "風邪薬"],
    ["prescription counter", "処方受付"],
    ["insurance card", "保険証"],
    ["doctor's office", "診察室"],
    ["tourist police", "観光警察"],
    ["lost passport", "紛失したパスポート"],
    ["incident report", "被害届 / 事故報告"],
    ["embassy staff", "大使館職員"],
    ["consulate", "領事館"],
    ["travel document", "渡航書類"],
    ["power adapter", "電源変換アダプター"],
    ["portable charger", "携帯充電器"],
    ["charging cable", "充電ケーブル"],
    ["SIM card", "SIMカード"],
    ["data plan", "通信プラン"],
    ["free Wi-Fi spot", "無料Wi-Fiスポット"],
    ["signal strength", "電波の強さ"],
    ["translation app", "翻訳アプリ"],
    ["offline map", "オフライン地図"],
    ["photo ticket", "写真付きチケット"],
    ["digital pass", "電子パス"],
    ["entry pass", "入場パス"],
    ["reentry", "再入場"],
    ["local tour", "現地ツアー"],
    ["meeting point", "集合場所"],
    ["departure time", "出発時刻"],
    ["return time", "帰着時刻"],
    ["travel plan", "旅行計画"],
    ["packing list", "持ち物リスト"],
    ["comfortable shoes", "歩きやすい靴"],
    ["spare clothes", "着替え"],
    ["travel bottle", "携帯用ボトル"],
    ["guide map", "案内図"],
    ["ticket line", "切符待ちの列"],
    ["admission counter", "入場窓口"],
    ["weekend crowd", "週末の混雑"],
    ["peak season", "繁忙期"],
    ["off season", "閑散期"],
    ["souvenir bag", "お土産袋"],
    ["shopping bag", "買い物袋"],
    ["carry case", "持ち運びケース"],
    ["local guide", "現地ガイド"],
    ["tour schedule", "観光日程"],
    ["rain cover", "雨よけカバー"],
    ["travel pillow", "旅行用まくら"],
    ["neck pillow", "ネックピロー"],
    ["hand towel", "ハンドタオル"],
    ["coin purse", "小銭入れ"],
    ["hotel voucher", "宿泊バウチャー"],
    ["reservation email", "予約確認メール"],
    ["confirmation slip", "確認票"],
    ["platform ticket", "入場券"],
    ["ticket inspector", "車掌 / 改札係"],
    ["arrival platform", "到着ホーム"],
    ["departure platform", "出発ホーム"],
    ["seat number", "座席番号"],
    ["window side", "窓側"],
    ["aisle side", "通路側"],
    ["middle seat", "中央席"],
    ["boarding line", "搭乗待ちの列"],
    ["security area", "保安区域"],
    ["arrival lounge", "到着ラウンジ"],
    ["baggage cart", "荷物カート"],
    ["airport hotel", "空港ホテル"],
    ["hotel entrance", "ホテル入口"],
    ["late-night check-in", "深夜チェックイン"],
    ["early-morning flight", "早朝便"],
    ["travel pass", "周遊パス"],
    ["seat map", "座席表"],
    ["route search", "経路検索"],
    ["transfer guide", "乗換案内"],
    ["travel route", "旅行ルート"],
    ["day trip", "日帰り旅行"],
    ["night bus", "夜行バス"],
    ["express bus", "高速バス"],
    ["ferry terminal", "フェリー乗り場"],
    ["boat ride", "船旅 / 船に乗ること"],
    ["water taxi", "水上タクシー"],
    ["bike rental", "自転車レンタル"],
    ["rental counter", "貸出カウンター"],
    ["return point", "返却場所"],
    ["public restroom", "公衆トイレ"],
    ["baby room", "授乳室 / ベビールーム"],
    ["family restroom", "多目的トイレ"],
    ["rest area", "休憩所"],
    ["waiting room", "待合室"],
    ["information board", "案内板"],
    ["city tour", "市内観光"],
    ["walking tour", "徒歩ツアー"],
    ["bus tour", "観光バスツアー"],
    ["tour ticket", "ツアーチケット"],
    ["entry ticket", "入場チケット"],
    ["museum shop", "ミュージアムショップ"],
    ["temple bell", "寺の鐘"],
    ["photo pass", "撮影パス"],
    ["viewing area", "見学エリア"],
    ["crowded season", "混む時期"],
    ["rainy season", "雨季"],
    ["hot spring", "温泉"],
    ["local bus", "路線バス"],
    ["bus stop sign", "バス停表示"],
    ["platform sign", "ホーム案内表示"],
    ["arrival board", "到着案内板"],
    ["departure board", "出発案内板"],
    ["train delay", "電車の遅れ"],
    ["service suspension", "運休"],
    ["late checkout fee", "延長料金"],
    ["check-in counter", "チェックインカウンター"],
    ["checkout counter", "チェックアウト窓口"],
    ["lobby lounge", "ロビーラウンジ"],
    ["room rate", "宿泊料金"],
    ["extra charge", "追加料金"],
    ["tap water safety", "水道水の安全性"],
    ["drink order", "飲み物の注文"],
    ["food allergy", "食物アレルギー"],
    ["table charge", "席料"],
    ["kitchen closing time", "ラストオーダー時間"],
    ["lost baggage", "紛失した手荷物"],
    ["lost phone", "なくした携帯電話"],
    ["travel schedule", "旅行日程"],
    ["travel companion", "旅行仲間"],
    ["return flight", "復路便"]
  ])
]);

export const vocabulary = {
  basic: {
    label: "初級",
    description: "中学生レベルの一般会話と生活の土台になる基本単語をまとめたカテゴリです。",
    words: basicWordsExpanded
  },
  practical: {
    label: "実用単語",
    description: "生活の手続き、説明、トラブル対応、スマホ操作など日常を広げる実用語彙です。",
    words: practicalWords
  },
  business: {
    label: "ビジネス",
    description: "会議、進行管理、メール、契約、運用など仕事で使う語彙をまとめたカテゴリです。",
    words: businessWordsExpanded
  },
  travel: {
    label: "旅行",
    description: "空港、交通、宿泊、観光、食事、トラブル対応で使う旅行語彙をまとめたカテゴリです。",
    words: travelWordsExpanded
  }
};

